
package com.vidal.CompositionService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CompositionService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/CompositionService.wsdl")
public class CompositionService_Service
    extends Service
{

    private final static URL COMPOSITIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPOSITIONSERVICE_EXCEPTION;
    private final static QName COMPOSITIONSERVICE_QNAME = new QName("urn:Vidal", "CompositionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/CompositionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPOSITIONSERVICE_WSDL_LOCATION = url;
        COMPOSITIONSERVICE_EXCEPTION = e;
    }

    public CompositionService_Service() {
        super(__getWsdlLocation(), COMPOSITIONSERVICE_QNAME);
    }

    public CompositionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CompositionService
     */
    @WebEndpoint(name = "CompositionServiceHttpPort")
    public CompositionService getCompositionServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "CompositionServiceHttpPort"), CompositionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompositionService
     */
    @WebEndpoint(name = "CompositionServiceHttpPort")
    public CompositionService getCompositionServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "CompositionServiceHttpPort"), CompositionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPOSITIONSERVICE_EXCEPTION!= null) {
            throw COMPOSITIONSERVICE_EXCEPTION;
        }
        return COMPOSITIONSERVICE_WSDL_LOCATION;
    }

}
