
package com.whatever.SaumonService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "saumonService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SaumonService {


    /**
     * 
     * @param saumonId
     * @return
     *     returns com.whatever.SaumonService.ArrayOfSaumon
     */
    @WebMethod
    @WebResult(name = "saumonList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.GetChildrenResponse")
    public ArrayOfSaumon getChildren(
        @WebParam(name = "saumonId", targetNamespace = "urn:Vidal")
        Integer saumonId);

    /**
     * 
     * @param saumonId
     * @return
     *     returns com.whatever.SaumonService.Saumon
     */
    @WebMethod
    @WebResult(name = "saumon", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.GetParentResponse")
    public Saumon getParent(
        @WebParam(name = "saumonId", targetNamespace = "urn:Vidal")
        Integer saumonId);

    /**
     * 
     * @return
     *     returns com.whatever.SaumonService.Saumon
     */
    @WebMethod
    @WebResult(name = "saumon", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.GetRootNodeResponse")
    public Saumon getRootNode();

    /**
     * 
     * @param saumonId
     * @return
     *     returns com.whatever.SaumonService.Saumon
     */
    @WebMethod
    @WebResult(name = "saumon", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.SearchByIdResponse")
    public Saumon searchById(
        @WebParam(name = "saumonId", targetNamespace = "urn:Vidal")
        Integer saumonId);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.SaumonService.ArrayOfSaumon
     */
    @WebMethod
    @WebResult(name = "saumonList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.SearchByNameResponse")
    public ArrayOfSaumon searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.SaumonService.ArrayOfSaumon
     */
    @WebMethod
    @WebResult(name = "saumonList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.SaumonService.SearchByProductIdResponse")
    public ArrayOfSaumon searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
