
package com.vidal.CodingService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "codingService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CodingService {


    /**
     * 
     * @param indicationGroupCleanParams
     * @param engine
     * @param cim10Codes
     * @param drugCodes
     * @param drugCursor
     * @param text
     * @return
     *     returns com.vidal.CodingService.ArrayOfPostComplementItem
     */
    @WebMethod
    @WebResult(name = "postComplementItemList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "postComplementWithDrugCodes", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostComplementWithDrugCodes")
    @ResponseWrapper(localName = "postComplementWithDrugCodesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostComplementWithDrugCodesResponse")
    public ArrayOfPostComplementItem postComplementWithDrugCodes(
        @WebParam(name = "text", targetNamespace = "urn:Vidal")
        String text,
        @WebParam(name = "cim10Codes", targetNamespace = "urn:Vidal")
        ArrayOfString cim10Codes,
        @WebParam(name = "drugCodes", targetNamespace = "urn:Vidal")
        ArrayOfString drugCodes,
        @WebParam(name = "engine", targetNamespace = "urn:Vidal")
        SearchEngine engine,
        @WebParam(name = "drugCursor", targetNamespace = "urn:Vidal")
        PmsiCursors drugCursor,
        @WebParam(name = "indicationGroupCleanParams", targetNamespace = "urn:Vidal")
        IndicationGroupCleanParams indicationGroupCleanParams);

    /**
     * 
     * @param prescriptionLines
     * @param indicationGroupCleanParams
     * @param engine
     * @param patient
     * @param drugCursor
     * @param text
     * @return
     *     returns com.vidal.CodingService.ArrayOfPostComplementItem
     */
    @WebMethod
    @WebResult(name = "postComplementItemList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "postComplementWithDrugs", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostComplementWithDrugs")
    @ResponseWrapper(localName = "postComplementWithDrugsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostComplementWithDrugsResponse")
    public ArrayOfPostComplementItem postComplementWithDrugs(
        @WebParam(name = "text", targetNamespace = "urn:Vidal")
        String text,
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        String patient,
        @WebParam(name = "prescriptionLines", targetNamespace = "urn:Vidal")
        ArrayOfString prescriptionLines,
        @WebParam(name = "engine", targetNamespace = "urn:Vidal")
        SearchEngine engine,
        @WebParam(name = "drugCursor", targetNamespace = "urn:Vidal")
        PmsiCursors drugCursor,
        @WebParam(name = "indicationGroupCleanParams", targetNamespace = "urn:Vidal")
        IndicationGroupCleanParams indicationGroupCleanParams);

    /**
     * 
     * @param engine
     * @param cim10Codes
     * @param drugCodes
     * @param drugCursor
     * @param text
     * @return
     *     returns com.vidal.CodingService.ArrayOfPostControlItem
     */
    @WebMethod
    @WebResult(name = "postControlItemList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "postControlWithDrugCodes", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostControlWithDrugCodes")
    @ResponseWrapper(localName = "postControlWithDrugCodesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostControlWithDrugCodesResponse")
    public ArrayOfPostControlItem postControlWithDrugCodes(
        @WebParam(name = "text", targetNamespace = "urn:Vidal")
        String text,
        @WebParam(name = "cim10Codes", targetNamespace = "urn:Vidal")
        ArrayOfString cim10Codes,
        @WebParam(name = "drugCodes", targetNamespace = "urn:Vidal")
        ArrayOfString drugCodes,
        @WebParam(name = "engine", targetNamespace = "urn:Vidal")
        SearchEngine engine,
        @WebParam(name = "drugCursor", targetNamespace = "urn:Vidal")
        PmsiCursors drugCursor);

    /**
     * 
     * @param prescriptionLines
     * @param engine
     * @param patient
     * @param drugCursor
     * @param text
     * @return
     *     returns com.vidal.CodingService.ArrayOfPostControlItem
     */
    @WebMethod
    @WebResult(name = "postControlItemList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "postControlWithDrugs", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostControlWithDrugs")
    @ResponseWrapper(localName = "postControlWithDrugsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.PostControlWithDrugsResponse")
    public ArrayOfPostControlItem postControlWithDrugs(
        @WebParam(name = "text", targetNamespace = "urn:Vidal")
        String text,
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        String patient,
        @WebParam(name = "prescriptionLines", targetNamespace = "urn:Vidal")
        ArrayOfString prescriptionLines,
        @WebParam(name = "engine", targetNamespace = "urn:Vidal")
        SearchEngine engine,
        @WebParam(name = "drugCursor", targetNamespace = "urn:Vidal")
        PmsiCursors drugCursor);

    /**
     * 
     * @param pageNumber
     * @param name
     * @param pageSize
     * @param aggregates
     * @return
     *     returns com.vidal.CodingService.PagedResultGroupResultFull
     */
    @WebMethod
    @WebResult(name = "pagedResultGroupResultFull", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCodingGroupResultFullWithAggregates", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.SearchCodingGroupResultFullWithAggregates")
    @ResponseWrapper(localName = "searchCodingGroupResultFullWithAggregatesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CodingService.SearchCodingGroupResultFullWithAggregatesResponse")
    public PagedResultGroupResultFull searchCodingGroupResultFullWithAggregates(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        ArrayOfGroupResultAggregate aggregates,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

}
