
package com.whatever.DocumentService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "documentService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentService {


    /**
     * 
     * @param packId
     * @param documentTypeList
     * @return
     *     returns com.whatever.DocumentService.ArrayOfDocument
     */
    @WebMethod
    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDocumentsByDocumentTypesForPackId", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.GetDocumentsByDocumentTypesForPackId")
    @ResponseWrapper(localName = "getDocumentsByDocumentTypesForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.GetDocumentsByDocumentTypesForPackIdResponse")
    public ArrayOfDocument getDocumentsByDocumentTypesForPackId(
        @WebParam(name = "documentTypeList", targetNamespace = "urn:Vidal")
        ArrayOfDocumentType documentTypeList,
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param productId
     * @param documentTypeList
     * @return
     *     returns com.whatever.DocumentService.ArrayOfDocument
     */
    @WebMethod
    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDocumentsByDocumentTypesForProductId", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.GetDocumentsByDocumentTypesForProductId")
    @ResponseWrapper(localName = "getDocumentsByDocumentTypesForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.GetDocumentsByDocumentTypesForProductIdResponse")
    public ArrayOfDocument getDocumentsByDocumentTypesForProductId(
        @WebParam(name = "documentTypeList", targetNamespace = "urn:Vidal")
        ArrayOfDocumentType documentTypeList,
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param documentTypeList
     * @param ucdId
     * @return
     *     returns com.whatever.DocumentService.ArrayOfDocument
     */
    @WebMethod
    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDocumentsByDocumentTypesForUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.GetDocumentsByDocumentTypesForUcdId")
    @ResponseWrapper(localName = "getDocumentsByDocumentTypesForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.GetDocumentsByDocumentTypesForUcdIdResponse")
    public ArrayOfDocument getDocumentsByDocumentTypesForUcdId(
        @WebParam(name = "documentTypeList", targetNamespace = "urn:Vidal")
        ArrayOfDocumentType documentTypeList,
        @WebParam(name = "UcdId", targetNamespace = "urn:Vidal")
        Integer ucdId);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.DocumentService.ArrayOfDocument
     */
    @WebMethod
    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DocumentService.SearchByCommonNameGroupIdResponse")
    public ArrayOfDocument searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

}
