
package com.whatever.UtilitiesService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "utilitiesService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilitiesService {


    /**
     * 
     * @param hmkIds
     * @return
     *     returns com.whatever.UtilitiesService.String2CompositeIdMap
     */
    @WebMethod
    @WebResult(name = "compositeIdMap", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCompositeIdFromHMK", targetNamespace = "urn:Vidal", className = "com.whatever.UtilitiesService.GetCompositeIdFromHMK")
    @ResponseWrapper(localName = "getCompositeIdFromHMKResponse", targetNamespace = "urn:Vidal", className = "com.whatever.UtilitiesService.GetCompositeIdFromHMKResponse")
    public String2CompositeIdMap getCompositeIdFromHMK(
        @WebParam(name = "hmkIds", targetNamespace = "urn:Vidal")
        ArrayOfString hmkIds);

    /**
     * 
     * @param hmkCiId
     * @return
     *     returns com.whatever.UtilitiesService.ArrayOfCompositeId
     */
    @WebMethod
    @WebResult(name = "compositeIdList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCompositeIdsFromHMKContraIndication", targetNamespace = "urn:Vidal", className = "com.whatever.UtilitiesService.GetCompositeIdsFromHMKContraIndication")
    @ResponseWrapper(localName = "getCompositeIdsFromHMKContraIndicationResponse", targetNamespace = "urn:Vidal", className = "com.whatever.UtilitiesService.GetCompositeIdsFromHMKContraIndicationResponse")
    public ArrayOfCompositeId getCompositeIdsFromHMKContraIndication(
        @WebParam(name = "hmkCiId", targetNamespace = "urn:Vidal")
        String hmkCiId);

}
