
package com.whatever.DrugInteractionClassService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DrugInteractionClassService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/DrugInteractionClassService.wsdl")
public class DrugInteractionClassService_Service
    extends Service
{

    private final static URL DRUGINTERACTIONCLASSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRUGINTERACTIONCLASSSERVICE_EXCEPTION;
    private final static QName DRUGINTERACTIONCLASSSERVICE_QNAME = new QName("urn:Vidal", "DrugInteractionClassService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/DrugInteractionClassService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRUGINTERACTIONCLASSSERVICE_WSDL_LOCATION = url;
        DRUGINTERACTIONCLASSSERVICE_EXCEPTION = e;
    }

    public DrugInteractionClassService_Service() {
        super(__getWsdlLocation(), DRUGINTERACTIONCLASSSERVICE_QNAME);
    }

    public DrugInteractionClassService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DrugInteractionClassService
     */
    @WebEndpoint(name = "DrugInteractionClassServiceHttpPort")
    public DrugInteractionClassService getDrugInteractionClassServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "DrugInteractionClassServiceHttpPort"), DrugInteractionClassService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DrugInteractionClassService
     */
    @WebEndpoint(name = "DrugInteractionClassServiceHttpPort")
    public DrugInteractionClassService getDrugInteractionClassServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "DrugInteractionClassServiceHttpPort"), DrugInteractionClassService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRUGINTERACTIONCLASSSERVICE_EXCEPTION!= null) {
            throw DRUGINTERACTIONCLASSSERVICE_EXCEPTION;
        }
        return DRUGINTERACTIONCLASSSERVICE_WSDL_LOCATION;
    }

}
