
package com.whatever.IndicationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "indicationService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IndicationService {


    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.IndicationService.PagedResultIndication
     */
    @WebMethod
    @WebResult(name = "pagedResultIndication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllIndications", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.GetAllIndications")
    @ResponseWrapper(localName = "getAllIndicationsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.GetAllIndicationsResponse")
    public PagedResultIndication getAllIndications(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param types
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.IndicationService.CommonNameGroupTypedIndication
     */
    @WebMethod
    @WebResult(name = "commonNameGroupTypedIndication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupIdAndType", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByCommonNameGroupIdAndType")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByCommonNameGroupIdAndTypeResponse")
    public CommonNameGroupTypedIndication searchByCommonNameGroupIdAndType(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfIndicationType types);

    /**
     * 
     * @param indicationId
     * @return
     *     returns com.whatever.IndicationService.Indication
     */
    @WebMethod
    @WebResult(name = "indication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByIdResponse")
    public Indication searchById(
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        Integer indicationId);

    /**
     * 
     * @param types
     * @param indicationGroupId
     * @return
     *     returns com.whatever.IndicationService.ArrayOfTypedIndication
     */
    @WebMethod
    @WebResult(name = "typedIndicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupIdAndType", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByIndicationGroupIdAndType")
    @ResponseWrapper(localName = "searchByIndicationGroupIdAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByIndicationGroupIdAndTypeResponse")
    public ArrayOfTypedIndication searchByIndicationGroupIdAndType(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        Integer indicationGroupId,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfIndicationType types);

    /**
     * 
     * @param types
     * @param name
     * @return
     *     returns com.whatever.IndicationService.ArrayOfTypedIndication
     */
    @WebMethod
    @WebResult(name = "typedIndicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameAndType", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByNameAndType")
    @ResponseWrapper(localName = "searchByNameAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByNameAndTypeResponse")
    public ArrayOfTypedIndication searchByNameAndType(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfIndicationType types);

    /**
     * 
     * @param types
     * @param productId
     * @return
     *     returns com.whatever.IndicationService.ProductTypedIndication
     */
    @WebMethod
    @WebResult(name = "productTypedIndication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductIdAndType", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByProductIdAndType")
    @ResponseWrapper(localName = "searchByProductIdAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchByProductIdAndTypeResponse")
    public ProductTypedIndication searchByProductIdAndType(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfIndicationType types);

    /**
     * 
     * @param pageNumber
     * @param codesLES
     * @param pageSize
     * @return
     *     returns com.whatever.IndicationService.PagedResultIndicationLES
     */
    @WebMethod
    @WebResult(name = "pagedResultIndicationLES", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchIndicationLESByCodes", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchIndicationLESByCodes")
    @ResponseWrapper(localName = "searchIndicationLESByCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchIndicationLESByCodesResponse")
    public PagedResultIndicationLES searchIndicationLESByCodes(
        @WebParam(name = "codesLES", targetNamespace = "urn:Vidal")
        ArrayOfString codesLES,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param indicationLESId
     * @return
     *     returns com.whatever.IndicationService.IndicationLes
     */
    @WebMethod
    @WebResult(name = "indicationLES", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchIndicationLESById", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchIndicationLESById")
    @ResponseWrapper(localName = "searchIndicationLESByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchIndicationLESByIdResponse")
    public IndicationLes searchIndicationLESById(
        @WebParam(name = "indicationLESId", targetNamespace = "urn:Vidal")
        Integer indicationLESId);

    /**
     * 
     * @param otherIndicationId
     * @return
     *     returns com.whatever.IndicationService.OtherIndication
     */
    @WebMethod
    @WebResult(name = "otherIndication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOtherIndicationById", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchOtherIndicationById")
    @ResponseWrapper(localName = "searchOtherIndicationByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchOtherIndicationByIdResponse")
    public OtherIndication searchOtherIndicationById(
        @WebParam(name = "otherIndicationId", targetNamespace = "urn:Vidal")
        Integer otherIndicationId);

    /**
     * 
     * @param codes
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.IndicationService.PagedResultOtherIndication
     */
    @WebMethod
    @WebResult(name = "pagedResultOtherIndication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOtherIndicationsByCodes", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchOtherIndicationsByCodes")
    @ResponseWrapper(localName = "searchOtherIndicationsByCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationService.SearchOtherIndicationsByCodesResponse")
    public PagedResultOtherIndication searchOtherIndicationsByCodes(
        @WebParam(name = "codes", targetNamespace = "urn:Vidal")
        ArrayOfString codes,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

}
