
package com.whatever.ProductRangeService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "productRangeService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductRangeService {


    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.ProductRangeService.PagedResultProductRange
     */
    @WebMethod
    @WebResult(name = "pagedResultProductRange", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllProductRanges", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.GetAllProductRanges")
    @ResponseWrapper(localName = "getAllProductRangesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.GetAllProductRangesResponse")
    public PagedResultProductRange getAllProductRanges(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param productRangeIds
     * @return
     *     returns com.whatever.ProductRangeService.ArrayOfProductRange
     */
    @WebMethod
    @WebResult(name = "productRangeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByIdsResponse")
    public ArrayOfProductRange searchByIds(
        @WebParam(name = "productRangeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productRangeIds);

    /**
     * 
     * @param productRangeName
     * @return
     *     returns com.whatever.ProductRangeService.ArrayOfProductRange
     */
    @WebMethod
    @WebResult(name = "productRangeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByNameResponse")
    public ArrayOfProductRange searchByName(
        @WebParam(name = "productRangeName", targetNamespace = "urn:Vidal")
        String productRangeName);

    /**
     * 
     * @param packIds
     * @return
     *     returns com.whatever.ProductRangeService.ArrayOfProductRangePackCouple
     */
    @WebMethod
    @WebResult(name = "productRangePackCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByPackIds")
    @ResponseWrapper(localName = "searchByPackIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByPackIdsResponse")
    public ArrayOfProductRangePackCouple searchByPackIds(
        @WebParam(name = "packIds", targetNamespace = "urn:Vidal")
        ArrayOfInt packIds);

    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.ProductRangeService.ArrayOfProductRangeProductCouple
     */
    @WebMethod
    @WebResult(name = "productRangeProductCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByProductIds")
    @ResponseWrapper(localName = "searchByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByProductIdsResponse")
    public ArrayOfProductRangeProductCouple searchByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

    /**
     * 
     * @param ucdIds
     * @return
     *     returns com.whatever.ProductRangeService.ArrayOfProductRangeUcdCouple
     */
    @WebMethod
    @WebResult(name = "productRangeUcdCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByUcdIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByUcdIds")
    @ResponseWrapper(localName = "searchByUcdIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductRangeService.SearchByUcdIdsResponse")
    public ArrayOfProductRangeUcdCouple searchByUcdIds(
        @WebParam(name = "ucdIds", targetNamespace = "urn:Vidal")
        ArrayOfInt ucdIds);

}
