
package com.whatever.ProductRangeService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductRangeService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/ProductRangeService.wsdl")
public class ProductRangeService_Service
    extends Service
{

    private final static URL PRODUCTRANGESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTRANGESERVICE_EXCEPTION;
    private final static QName PRODUCTRANGESERVICE_QNAME = new QName("urn:Vidal", "ProductRangeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/ProductRangeService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTRANGESERVICE_WSDL_LOCATION = url;
        PRODUCTRANGESERVICE_EXCEPTION = e;
    }

    public ProductRangeService_Service() {
        super(__getWsdlLocation(), PRODUCTRANGESERVICE_QNAME);
    }

    public ProductRangeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ProductRangeService
     */
    @WebEndpoint(name = "ProductRangeServiceHttpPort")
    public ProductRangeService getProductRangeServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "ProductRangeServiceHttpPort"), ProductRangeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductRangeService
     */
    @WebEndpoint(name = "ProductRangeServiceHttpPort")
    public ProductRangeService getProductRangeServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "ProductRangeServiceHttpPort"), ProductRangeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTRANGESERVICE_EXCEPTION!= null) {
            throw PRODUCTRANGESERVICE_EXCEPTION;
        }
        return PRODUCTRANGESERVICE_WSDL_LOCATION;
    }

}
