
package com.vidal.LpprService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LpprService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/LpprService.wsdl")
public class LpprService_Service
    extends Service
{

    private final static URL LPPRSERVICE_WSDL_LOCATION;
    private final static WebServiceException LPPRSERVICE_EXCEPTION;
    private final static QName LPPRSERVICE_QNAME = new QName("urn:Vidal", "LpprService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/LpprService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LPPRSERVICE_WSDL_LOCATION = url;
        LPPRSERVICE_EXCEPTION = e;
    }

    public LpprService_Service() {
        super(__getWsdlLocation(), LPPRSERVICE_QNAME);
    }

    public LpprService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns LpprService
     */
    @WebEndpoint(name = "LpprServiceHttpPort")
    public LpprService getLpprServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "LpprServiceHttpPort"), LpprService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LpprService
     */
    @WebEndpoint(name = "LpprServiceHttpPort")
    public LpprService getLpprServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "LpprServiceHttpPort"), LpprService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LPPRSERVICE_EXCEPTION!= null) {
            throw LPPRSERVICE_EXCEPTION;
        }
        return LPPRSERVICE_WSDL_LOCATION;
    }

}
