
package com.whatever.ProductService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "productService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "directSearchByName", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.DirectSearchByName")
    @ResponseWrapper(localName = "directSearchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.DirectSearchByNameResponse")
    public ArrayOfProduct directSearchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param types
     * @param pageNumber
     * @param name
     * @param pageSize
     * @param marketStatuses
     * @param aggregates
     * @param productApiFilter
     * @return
     *     returns com.whatever.ProductService.PagedResultProductFull
     */
    @WebMethod
    @WebResult(name = "pagedResultProductFull", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllProductFull", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetAllProductFull")
    @ResponseWrapper(localName = "getAllProductFullResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetAllProductFullResponse")
    public PagedResultProductFull getAllProductFull(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "productApiFilter", targetNamespace = "urn:Vidal")
        ProductApiFilter productApiFilter,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfProductType types,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        ArrayOfAggregate aggregates,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param types
     * @param pageNumber
     * @param pageSize
     * @param marketStatuses
     * @param productApiFilter
     * @return
     *     returns com.whatever.ProductService.PagedResultProduct
     */
    @WebMethod
    @WebResult(name = "pagedResultProduct", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetAllProductsResponse")
    public PagedResultProduct getAllProducts(
        @WebParam(name = "productApiFilter", targetNamespace = "urn:Vidal")
        ProductApiFilter productApiFilter,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfProductType types,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param productIds
     * @param aggregates
     * @return
     *     returns com.whatever.ProductService.ArrayOfProductFull
     */
    @WebMethod
    @WebResult(name = "productFullList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getProductFullByIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetProductFullByIds")
    @ResponseWrapper(localName = "getProductFullByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetProductFullByIdsResponse")
    public ArrayOfProductFull getProductFullByIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        ArrayOfAggregate aggregates);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.ProductService.RestrictedPrescriptions
     */
    @WebMethod
    @WebResult(name = "restrictedPrescriptions", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRestrictedPrescriptions", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetRestrictedPrescriptions")
    @ResponseWrapper(localName = "getRestrictedPrescriptionsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetRestrictedPrescriptionsResponse")
    public RestrictedPrescriptions getRestrictedPrescriptions(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.ProductService.ArrayOfConvertibleUnit
     */
    @WebMethod
    @WebResult(name = "convertibleUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getUnits", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetUnits")
    @ResponseWrapper(localName = "getUnitsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.GetUnitsResponse")
    public ArrayOfConvertibleUnit getUnits(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        int productId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.ProductService.SafetyAlertStatus
     */
    @WebMethod
    @WebResult(name = "safetyAlertStatus", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "hasCommonNameGroupSafetyAlert", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.HasCommonNameGroupSafetyAlert")
    @ResponseWrapper(localName = "hasCommonNameGroupSafetyAlertResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.HasCommonNameGroupSafetyAlertResponse")
    public SafetyAlertStatus hasCommonNameGroupSafetyAlert(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param aldId
     * @return
     *     returns com.whatever.ProductService.PagedResultProduct
     */
    @WebMethod
    @WebResult(name = "pagedResultProductByAld", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAldId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByAldId")
    @ResponseWrapper(localName = "searchByAldIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByAldIdResponse")
    public PagedResultProduct searchByAldId(
        @WebParam(name = "aldId", targetNamespace = "urn:Vidal")
        Integer aldId,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param atcIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAtcIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByAtcIds")
    @ResponseWrapper(localName = "searchByAtcIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByAtcIdsResponse")
    public ArrayOfProduct searchByAtcIds(
        @WebParam(name = "atcIds", targetNamespace = "urn:Vidal")
        ArrayOfInt atcIds);

    /**
     * 
     * @param pageNumber
     * @param biosimilarGroupId
     * @param pageSize
     * @return
     *     returns com.whatever.ProductService.PagedResultProductBiosimilarTypeCouple
     */
    @WebMethod
    @WebResult(name = "pagedResultProductBiosimilarTypeCouple", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByBiosimilarGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByBiosimilarGroupId")
    @ResponseWrapper(localName = "searchByBiosimilarGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByBiosimilarGroupIdResponse")
    public PagedResultProductBiosimilarTypeCouple searchByBiosimilarGroupId(
        @WebParam(name = "biosimilarGroupId", targetNamespace = "urn:Vidal")
        Integer biosimilarGroupId,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param cis
     * @return
     *     returns com.whatever.ProductService.Product
     */
    @WebMethod
    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCis", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCis")
    @ResponseWrapper(localName = "searchByCisResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCisResponse")
    public Product searchByCis(
        @WebParam(name = "cis", targetNamespace = "urn:Vidal")
        String cis);

    /**
     * 
     * @param cis
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCodes", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCodes")
    @ResponseWrapper(localName = "searchByCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCodesResponse")
    public ArrayOfProduct searchByCodes(
        @WebParam(name = "cis", targetNamespace = "urn:Vidal")
        ArrayOfString cis);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCommonNameGroupIdResponse")
    public ArrayOfProduct searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param companyId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCompanyId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCompanyId")
    @ResponseWrapper(localName = "searchByCompanyIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByCompanyIdResponse")
    public ArrayOfProduct searchByCompanyId(
        @WebParam(name = "companyId", targetNamespace = "urn:Vidal")
        Integer companyId);

    /**
     * 
     * @param contraIndicationId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByContraIndicationId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByContraIndicationId")
    @ResponseWrapper(localName = "searchByContraIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByContraIndicationIdResponse")
    public ArrayOfProduct searchByContraIndicationId(
        @WebParam(name = "contraIndicationId", targetNamespace = "urn:Vidal")
        Integer contraIndicationId);

    /**
     * 
     * @param drugInteractionClassId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByDrugInteractionClassId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByDrugInteractionClassId")
    @ResponseWrapper(localName = "searchByDrugInteractionClassIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByDrugInteractionClassIdResponse")
    public ArrayOfProduct searchByDrugInteractionClassId(
        @WebParam(name = "drugInteractionClassId", targetNamespace = "urn:Vidal")
        Integer drugInteractionClassId);

    /**
     * 
     * @param ephmraId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByEphmraId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByEphmraId")
    @ResponseWrapper(localName = "searchByEphmraIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByEphmraIdResponse")
    public ArrayOfProduct searchByEphmraId(
        @WebParam(name = "ephmraId", targetNamespace = "urn:Vidal")
        Integer ephmraId);

    /**
     * 
     * @param foodInteractionId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByFoodInteractionId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByFoodInteractionId")
    @ResponseWrapper(localName = "searchByFoodInteractionIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByFoodInteractionIdResponse")
    public ArrayOfProduct searchByFoodInteractionId(
        @WebParam(name = "foodInteractionId", targetNamespace = "urn:Vidal")
        Integer foodInteractionId);

    /**
     * 
     * @param genericGroupId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByGenericGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByGenericGroupId")
    @ResponseWrapper(localName = "searchByGenericGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByGenericGroupIdResponse")
    public ArrayOfProduct searchByGenericGroupId(
        @WebParam(name = "genericGroupId", targetNamespace = "urn:Vidal")
        Integer genericGroupId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.ProductService.Product
     */
    @WebMethod
    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIdResponse")
    public Product searchById(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIdsResponse")
    public ArrayOfProduct searchByIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

    /**
     * 
     * @param indicationGroupId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicationGroupIdResponse")
    public ArrayOfProduct searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        Integer indicationGroupId);

    /**
     * 
     * @param indicationId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicationId")
    @ResponseWrapper(localName = "searchByIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicationIdResponse")
    public ArrayOfProduct searchByIndicationId(
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        Integer indicationId);

    /**
     * 
     * @param indicationLESCode
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.ProductService.PagedResultProduct
     */
    @WebMethod
    @WebResult(name = "pagedResultProductByIndicationLESCode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationLESCode", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicationLESCode")
    @ResponseWrapper(localName = "searchByIndicationLESCodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicationLESCodeResponse")
    public PagedResultProduct searchByIndicationLESCode(
        @WebParam(name = "indicationLESCode", targetNamespace = "urn:Vidal")
        String indicationLESCode,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param operatorType
     * @param indicators
     * @return
     *     returns com.whatever.ProductService.PagedResultProduct
     */
    @WebMethod
    @WebResult(name = "pagedResultProductByIndicators", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicatorIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicatorIds")
    @ResponseWrapper(localName = "searchByIndicatorIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByIndicatorIdsResponse")
    public PagedResultProduct searchByIndicatorIds(
        @WebParam(name = "indicators", targetNamespace = "urn:Vidal")
        ArrayOfInt indicators,
        @WebParam(name = "operatorType", targetNamespace = "urn:Vidal")
        SetOperatorType operatorType,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param substanceType
     * @param moleculeId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMoleculeIdAndType", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByMoleculeIdAndType")
    @ResponseWrapper(localName = "searchByMoleculeIdAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByMoleculeIdAndTypeResponse")
    public ArrayOfProduct searchByMoleculeIdAndType(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        Integer moleculeId,
        @WebParam(name = "substanceType", targetNamespace = "urn:Vidal")
        SubstanceType substanceType);

    /**
     * 
     * @param substanceTypes
     * @param moleculeIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMoleculeIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByMoleculeIds")
    @ResponseWrapper(localName = "searchByMoleculeIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByMoleculeIdsResponse")
    public ArrayOfProduct searchByMoleculeIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt moleculeIds,
        @WebParam(name = "substanceTypes", targetNamespace = "urn:Vidal")
        ArrayOfSubstanceType substanceTypes);

    /**
     * 
     * @param types
     * @param pageNumber
     * @param name
     * @param pageSize
     * @param marketStatuses
     * @return
     *     returns com.whatever.ProductService.PagedResultProduct
     */
    @WebMethod
    @WebResult(name = "pagedResultProduct", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameWithPagedResult", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByNameWithPagedResult")
    @ResponseWrapper(localName = "searchByNameWithPagedResultResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByNameWithPagedResultResponse")
    public PagedResultProduct searchByNameWithPagedResult(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfProductType types,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param otherIndicationCode
     * @param pageSize
     * @return
     *     returns com.whatever.ProductService.PagedResultProduct
     */
    @WebMethod
    @WebResult(name = "pagedResultProductByOtherIndicationCode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByOtherIndicationCode", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByOtherIndicationCode")
    @ResponseWrapper(localName = "searchByOtherIndicationCodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByOtherIndicationCodeResponse")
    public PagedResultProduct searchByOtherIndicationCode(
        @WebParam(name = "otherIndicationCode", targetNamespace = "urn:Vidal")
        String otherIndicationCode,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param packId
     * @return
     *     returns com.whatever.ProductService.Product
     */
    @WebMethod
    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByPackIdResponse")
    public Product searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param precautionId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPrecautionId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByPrecautionId")
    @ResponseWrapper(localName = "searchByPrecautionIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByPrecautionIdResponse")
    public ArrayOfProduct searchByPrecautionId(
        @WebParam(name = "precautionId", targetNamespace = "urn:Vidal")
        Integer precautionId);

    /**
     * 
     * @param productRangeIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProductRangeProductCouple
     */
    @WebMethod
    @WebResult(name = "ProductRangeProductCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductRangeIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByProductRangeIds")
    @ResponseWrapper(localName = "searchByProductRangeIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByProductRangeIdsResponse")
    public ArrayOfProductRangeProductCouple searchByProductRangeIds(
        @WebParam(name = "productRangeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productRangeIds);

    /**
     * 
     * @param saumonIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySaumonIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchBySaumonIds")
    @ResponseWrapper(localName = "searchBySaumonIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchBySaumonIdsResponse")
    public ArrayOfProduct searchBySaumonIds(
        @WebParam(name = "saumonIds", targetNamespace = "urn:Vidal")
        ArrayOfInt saumonIds);

    /**
     * 
     * @param sempIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySempIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchBySempIds")
    @ResponseWrapper(localName = "searchBySempIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchBySempIdsResponse")
    public ArrayOfProduct searchBySempIds(
        @WebParam(name = "sempIds", targetNamespace = "urn:Vidal")
        ArrayOfInt sempIds);

    /**
     * 
     * @param sideEffectId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySideEffectId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchBySideEffectId")
    @ResponseWrapper(localName = "searchBySideEffectIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchBySideEffectIdResponse")
    public ArrayOfProduct searchBySideEffectId(
        @WebParam(name = "sideEffectId", targetNamespace = "urn:Vidal")
        Integer sideEffectId);

    /**
     * 
     * @param ucdId
     * @return
     *     returns com.whatever.ProductService.Product
     */
    @WebMethod
    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByUcdId")
    @ResponseWrapper(localName = "searchByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByUcdIdResponse")
    public Product searchByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        Integer ucdId);

    /**
     * 
     * @param vidalIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByVidalIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByVidalIds")
    @ResponseWrapper(localName = "searchByVidalIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByVidalIdsResponse")
    public ArrayOfProduct searchByVidalIds(
        @WebParam(name = "vidalIds", targetNamespace = "urn:Vidal")
        ArrayOfInt vidalIds);

    /**
     * 
     * @param warningId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByWarningId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByWarningId")
    @ResponseWrapper(localName = "searchByWarningIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchByWarningIdResponse")
    public ArrayOfProduct searchByWarningId(
        @WebParam(name = "warningId", targetNamespace = "urn:Vidal")
        Integer warningId);

    /**
     * 
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNewlyAvailableProducts", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchNewlyAvailableProducts")
    @ResponseWrapper(localName = "searchNewlyAvailableProductsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchNewlyAvailableProductsResponse")
    public ArrayOfProduct searchNewlyAvailableProducts();

    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProductIndicators
     */
    @WebMethod
    @WebResult(name = "productIndicatorsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchProductIndicatorsByProductIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchProductIndicatorsByProductIds")
    @ResponseWrapper(localName = "searchProductIndicatorsByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchProductIndicatorsByProductIdsResponse")
    public ArrayOfProductIndicators searchProductIndicatorsByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.ProductService.ArrayOfProductRouteListCouple
     */
    @WebMethod
    @WebResult(name = "ProductRouteListCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchProductRoutesCouplesByProductIds", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchProductRoutesCouplesByProductIds")
    @ResponseWrapper(localName = "searchProductRoutesCouplesByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchProductRoutesCouplesByProductIdsResponse")
    public ArrayOfProductRouteListCouple searchProductRoutesCouplesByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

    /**
     * 
     * @param ucdId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchProductsByUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchProductsByUcdId")
    @ResponseWrapper(localName = "searchProductsByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchProductsByUcdIdResponse")
    public ArrayOfProduct searchProductsByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        Integer ucdId);

    /**
     * 
     * @param productIds
     * @param indicationId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchWithoutInteractionsByIndicationId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchWithoutInteractionsByIndicationId")
    @ResponseWrapper(localName = "searchWithoutInteractionsByIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchWithoutInteractionsByIndicationIdResponse")
    public ArrayOfProduct searchWithoutInteractionsByIndicationId(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds,
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        Integer indicationId);

    /**
     * 
     * @param productIds
     * @param vidalId
     * @return
     *     returns com.whatever.ProductService.ArrayOfProduct
     */
    @WebMethod
    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchWithoutInteractionsByVidalId", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchWithoutInteractionsByVidalId")
    @ResponseWrapper(localName = "searchWithoutInteractionsByVidalIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.ProductService.SearchWithoutInteractionsByVidalIdResponse")
    public ArrayOfProduct searchWithoutInteractionsByVidalId(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds,
        @WebParam(name = "vidalId", targetNamespace = "urn:Vidal")
        Integer vidalId);

}
