
package com.vidal.NewsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "newsService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewsService {


    /**
     * 
     * @param typeIds
     * @param subTypeIds
     * @param profiles
     * @param limit
     * @param startDate
     * @return
     *     returns com.vidal.NewsService.ArrayOfNews
     */
    @WebMethod
    @WebResult(name = "newsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNews", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNews")
    @ResponseWrapper(localName = "searchNewsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsResponse")
    public ArrayOfNews searchNews(
        @WebParam(name = "typeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt typeIds,
        @WebParam(name = "subTypeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt subTypeIds,
        @WebParam(name = "profiles", targetNamespace = "urn:Vidal")
        ArrayOfProfile profiles,
        @WebParam(name = "limit", targetNamespace = "urn:Vidal")
        Integer limit,
        @WebParam(name = "startDate", targetNamespace = "urn:Vidal")
        XMLGregorianCalendar startDate);

    /**
     * 
     * @param newsId
     * @return
     *     returns com.vidal.NewsService.News
     */
    @WebMethod
    @WebResult(name = "news", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNewsById", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsById")
    @ResponseWrapper(localName = "searchNewsByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsByIdResponse")
    public News searchNewsById(
        @WebParam(name = "newsId", targetNamespace = "urn:Vidal")
        Integer newsId);

    /**
     * 
     * @param moleculeId
     * @return
     *     returns com.vidal.NewsService.ArrayOfNews
     */
    @WebMethod
    @WebResult(name = "newsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNewsByMoleculeId", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsByMoleculeId")
    @ResponseWrapper(localName = "searchNewsByMoleculeIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsByMoleculeIdResponse")
    public ArrayOfNews searchNewsByMoleculeId(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        Integer moleculeId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.NewsService.ArrayOfNews
     */
    @WebMethod
    @WebResult(name = "newsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNewsByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsByProductId")
    @ResponseWrapper(localName = "searchNewsByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.NewsService.SearchNewsByProductIdResponse")
    public ArrayOfNews searchNewsByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
