
package com.vidal.DrugPrescriptionAnalysisService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DrugPrescriptionAnalysisService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/DrugPrescriptionAnalysisService.wsdl")
public class DrugPrescriptionAnalysisService_Service
    extends Service
{

    private final static URL DRUGPRESCRIPTIONANALYSISSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRUGPRESCRIPTIONANALYSISSERVICE_EXCEPTION;
    private final static QName DRUGPRESCRIPTIONANALYSISSERVICE_QNAME = new QName("urn:Vidal", "DrugPrescriptionAnalysisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/DrugPrescriptionAnalysisService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRUGPRESCRIPTIONANALYSISSERVICE_WSDL_LOCATION = url;
        DRUGPRESCRIPTIONANALYSISSERVICE_EXCEPTION = e;
    }

    public DrugPrescriptionAnalysisService_Service() {
        super(__getWsdlLocation(), DRUGPRESCRIPTIONANALYSISSERVICE_QNAME);
    }

    public DrugPrescriptionAnalysisService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DrugPrescriptionAnalysisService
     */
    @WebEndpoint(name = "DrugPrescriptionAnalysisServiceHttpPort")
    public DrugPrescriptionAnalysisService getDrugPrescriptionAnalysisServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "DrugPrescriptionAnalysisServiceHttpPort"), DrugPrescriptionAnalysisService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DrugPrescriptionAnalysisService
     */
    @WebEndpoint(name = "DrugPrescriptionAnalysisServiceHttpPort")
    public DrugPrescriptionAnalysisService getDrugPrescriptionAnalysisServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "DrugPrescriptionAnalysisServiceHttpPort"), DrugPrescriptionAnalysisService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRUGPRESCRIPTIONANALYSISSERVICE_EXCEPTION!= null) {
            throw DRUGPRESCRIPTIONANALYSISSERVICE_EXCEPTION;
        }
        return DRUGPRESCRIPTIONANALYSISSERVICE_WSDL_LOCATION;
    }

}
