
package com.vidal.CompanyService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "companyService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompanyService {


    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.vidal.CompanyService.PagedResultCompany
     */
    @WebMethod
    @WebResult(name = "pagedResultCompany", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllCompanies", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.GetAllCompanies")
    @ResponseWrapper(localName = "getAllCompaniesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.GetAllCompaniesResponse")
    public PagedResultCompany getAllCompanies(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param companyId
     * @return
     *     returns com.vidal.CompanyService.Company
     */
    @WebMethod
    @WebResult(name = "company", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByIdResponse")
    public Company searchById(
        @WebParam(name = "companyId", targetNamespace = "urn:Vidal")
        Integer companyId);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.CompanyService.ArrayOfCompany
     */
    @WebMethod
    @WebResult(name = "companyList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByNameResponse")
    public ArrayOfCompany searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param packId
     * @return
     *     returns com.vidal.CompanyService.ArrayOfCompanyCompanyTypeCouple
     */
    @WebMethod
    @WebResult(name = "companyCompanyTypeCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByPackIdResponse")
    public ArrayOfCompanyCompanyTypeCouple searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.CompanyService.Company
     */
    @WebMethod
    @WebResult(name = "company", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CompanyService.SearchByProductIdResponse")
    public Company searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
