
package com.whatever.DatabaseInfoService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DatabaseInfoService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/DatabaseInfoService.wsdl")
public class DatabaseInfoService_Service
    extends Service
{

    private final static URL DATABASEINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATABASEINFOSERVICE_EXCEPTION;
    private final static QName DATABASEINFOSERVICE_QNAME = new QName("urn:Vidal", "DatabaseInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/DatabaseInfoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATABASEINFOSERVICE_WSDL_LOCATION = url;
        DATABASEINFOSERVICE_EXCEPTION = e;
    }

    public DatabaseInfoService_Service() {
        super(__getWsdlLocation(), DATABASEINFOSERVICE_QNAME);
    }

    public DatabaseInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DatabaseInfoService
     */
    @WebEndpoint(name = "DatabaseInfoServiceHttpPort")
    public DatabaseInfoService getDatabaseInfoServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "DatabaseInfoServiceHttpPort"), DatabaseInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DatabaseInfoService
     */
    @WebEndpoint(name = "DatabaseInfoServiceHttpPort")
    public DatabaseInfoService getDatabaseInfoServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "DatabaseInfoServiceHttpPort"), DatabaseInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATABASEINFOSERVICE_EXCEPTION!= null) {
            throw DATABASEINFOSERVICE_EXCEPTION;
        }
        return DATABASEINFOSERVICE_WSDL_LOCATION;
    }

}
