
package com.whatever.DatabaseInfoService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "databaseInfoService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DatabaseInfoService {


    /**
     * 
     * @param lapVersion
     * @param codeAdeli
     * @param userType
     * @param codeRpps
     * @param codeUserLap
     * @param codeLap
     * @return
     *     returns com.whatever.DatabaseInfoService.VIDALAuthStatus
     */
    @WebMethod
    @WebResult(name = "checkUser", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "checkUser", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.CheckUserResponse")
    public VIDALAuthStatus checkUser(
        @WebParam(name = "codeUserLap", targetNamespace = "urn:Vidal")
        String codeUserLap,
        @WebParam(name = "codeLap", targetNamespace = "urn:Vidal")
        String codeLap,
        @WebParam(name = "lapVersion", targetNamespace = "urn:Vidal")
        String lapVersion,
        @WebParam(name = "userType", targetNamespace = "urn:Vidal")
        String userType,
        @WebParam(name = "codeRpps", targetNamespace = "urn:Vidal")
        String codeRpps,
        @WebParam(name = "codeAdeli", targetNamespace = "urn:Vidal")
        String codeAdeli);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "CeMarkingLabel", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCEMarkingLabel", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetCEMarkingLabel")
    @ResponseWrapper(localName = "getCEMarkingLabelResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetCEMarkingLabelResponse")
    public String getCEMarkingLabel();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "expiryDate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDataExpiryDate", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetDataExpiryDate")
    @ResponseWrapper(localName = "getDataExpiryDateResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetDataExpiryDateResponse")
    public XMLGregorianCalendar getDataExpiryDate();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "extractionDate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getExtractionDate", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetExtractionDate")
    @ResponseWrapper(localName = "getExtractionDateResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetExtractionDateResponse")
    public XMLGregorianCalendar getExtractionDate();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "graceEndDate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getGraceEndDate", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetGraceEndDate")
    @ResponseWrapper(localName = "getGraceEndDateResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetGraceEndDateResponse")
    public XMLGregorianCalendar getGraceEndDate();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "licenceEndDate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getLicenceEndDate", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetLicenceEndDate")
    @ResponseWrapper(localName = "getLicenceEndDateResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetLicenceEndDateResponse")
    public XMLGregorianCalendar getLicenceEndDate();

    /**
     * 
     * @return
     *     returns com.whatever.DatabaseInfoService.LicencingStatus
     */
    @WebMethod
    @WebResult(name = "licenceOrGraceStatus", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getLicenceOrGraceStatus", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetLicenceOrGraceStatus")
    @ResponseWrapper(localName = "getLicenceOrGraceStatusResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetLicenceOrGraceStatusResponse")
    public LicencingStatus getLicenceOrGraceStatus();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "licenceStartDate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getLicenceStartDate", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetLicenceStartDate")
    @ResponseWrapper(localName = "getLicenceStartDateResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetLicenceStartDateResponse")
    public XMLGregorianCalendar getLicenceStartDate();

    /**
     * 
     * @return
     *     returns com.whatever.DatabaseInfoService.ProductLineType
     */
    @WebMethod
    @WebResult(name = "productLine", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getProductLine", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetProductLine")
    @ResponseWrapper(localName = "getProductLineResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetProductLineResponse")
    public ProductLineType getProductLine();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "version", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVersion", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "warningDate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getWarningDate", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetWarningDate")
    @ResponseWrapper(localName = "getWarningDateResponse", targetNamespace = "urn:Vidal", className = "com.whatever.DatabaseInfoService.GetWarningDateResponse")
    public XMLGregorianCalendar getWarningDate();

}
