
package com.whatever.PhysicoChemicalInteractionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "physicoChemicalInteractionService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhysicoChemicalInteractionService {


    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.PhysicoChemicalInteractionService.ArrayOfPhysicoChemicalInteractionCommentCouple
     */
    @WebMethod
    @WebResult(name = "physicoChemicalInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.PhysicoChemicalInteractionService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PhysicoChemicalInteractionService.SearchByCommonNameGroupIdResponse")
    public ArrayOfPhysicoChemicalInteractionCommentCouple searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param physicoChemicalInteractionId
     * @return
     *     returns com.whatever.PhysicoChemicalInteractionService.PhysicoChemicalInteraction
     */
    @WebMethod
    @WebResult(name = "physicoChemicalInteraction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.PhysicoChemicalInteractionService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PhysicoChemicalInteractionService.SearchByIdResponse")
    public PhysicoChemicalInteraction searchById(
        @WebParam(name = "physicoChemicalInteractionId", targetNamespace = "urn:Vidal")
        Integer physicoChemicalInteractionId);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.PhysicoChemicalInteractionService.ArrayOfPhysicoChemicalInteraction
     */
    @WebMethod
    @WebResult(name = "physicoChemicalInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.PhysicoChemicalInteractionService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PhysicoChemicalInteractionService.SearchByNameResponse")
    public ArrayOfPhysicoChemicalInteraction searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

}
