
package com.whatever.AsmrService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AsmrService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/AsmrService.wsdl")
public class AsmrService_Service
    extends Service
{

    private final static URL ASMRSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASMRSERVICE_EXCEPTION;
    private final static QName ASMRSERVICE_QNAME = new QName("urn:Vidal", "AsmrService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/AsmrService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASMRSERVICE_WSDL_LOCATION = url;
        ASMRSERVICE_EXCEPTION = e;
    }

    public AsmrService_Service() {
        super(__getWsdlLocation(), ASMRSERVICE_QNAME);
    }

    public AsmrService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AsmrService
     */
    @WebEndpoint(name = "AsmrServiceHttpPort")
    public AsmrService getAsmrServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "AsmrServiceHttpPort"), AsmrService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsmrService
     */
    @WebEndpoint(name = "AsmrServiceHttpPort")
    public AsmrService getAsmrServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "AsmrServiceHttpPort"), AsmrService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASMRSERVICE_EXCEPTION!= null) {
            throw ASMRSERVICE_EXCEPTION;
        }
        return ASMRSERVICE_WSDL_LOCATION;
    }

}
