
package com.whatever.PosologyService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PosologyService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/PosologyService.wsdl")
public class PosologyService_Service
    extends Service
{

    private final static URL POSOLOGYSERVICE_WSDL_LOCATION;
    private final static WebServiceException POSOLOGYSERVICE_EXCEPTION;
    private final static QName POSOLOGYSERVICE_QNAME = new QName("urn:Vidal", "PosologyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/PosologyService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSOLOGYSERVICE_WSDL_LOCATION = url;
        POSOLOGYSERVICE_EXCEPTION = e;
    }

    public PosologyService_Service() {
        super(__getWsdlLocation(), POSOLOGYSERVICE_QNAME);
    }

    public PosologyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PosologyService
     */
    @WebEndpoint(name = "PosologyServiceHttpPort")
    public PosologyService getPosologyServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "PosologyServiceHttpPort"), PosologyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PosologyService
     */
    @WebEndpoint(name = "PosologyServiceHttpPort")
    public PosologyService getPosologyServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "PosologyServiceHttpPort"), PosologyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSOLOGYSERVICE_EXCEPTION!= null) {
            throw POSOLOGYSERVICE_EXCEPTION;
        }
        return POSOLOGYSERVICE_WSDL_LOCATION;
    }

}
