
package com.whatever.PosologyService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "posologyService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PosologyService {


    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.PosologyService.PagedResultUnit
     */
    @WebMethod
    @WebResult(name = "pagedResultUnit", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllUnits", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetAllUnits")
    @ResponseWrapper(localName = "getAllUnitsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetAllUnitsResponse")
    public PagedResultUnit getAllUnits(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param productId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ammPosology", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAmmPosologyByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetAmmPosologyByProductId")
    @ResponseWrapper(localName = "getAmmPosologyByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetAmmPosologyByProductIdResponse")
    public String getAmmPosologyByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param unitIds
     * @return
     *     returns com.whatever.PosologyService.ArrayOfPosologyUnit
     */
    @WebMethod
    @WebResult(name = "posologyUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPosologyUnitsByIds", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetPosologyUnitsByIds")
    @ResponseWrapper(localName = "getPosologyUnitsByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetPosologyUnitsByIdsResponse")
    public ArrayOfPosologyUnit getPosologyUnitsByIds(
        @WebParam(name = "unitIds", targetNamespace = "urn:Vidal")
        ArrayOfInt unitIds);

    /**
     * 
     * @param unitIds
     * @return
     *     returns com.whatever.PosologyService.ArrayOfPosologyUnit
     */
    @WebMethod
    @WebResult(name = "posologyUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRelatedPosologyUnitsByIds", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetRelatedPosologyUnitsByIds")
    @ResponseWrapper(localName = "getRelatedPosologyUnitsByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.GetRelatedPosologyUnitsByIdsResponse")
    public ArrayOfPosologyUnit getRelatedPosologyUnitsByIds(
        @WebParam(name = "unitIds", targetNamespace = "urn:Vidal")
        ArrayOfInt unitIds);

    /**
     * 
     * @param hepaticInsufficiency
     * @param indicationIds
     * @param gender
     * @param commonNameGroupId
     * @param creatinClearance
     * @param weight
     * @param age
     * @param height
     * @return
     *     returns com.whatever.PosologyService.CommonNameGroupPosologyRouteList
     */
    @WebMethod
    @WebResult(name = "posologyRouteList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPosologyRouteByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPosologyRouteByCommonNameGroupId")
    @ResponseWrapper(localName = "searchPosologyRouteByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPosologyRouteByCommonNameGroupIdResponse")
    public CommonNameGroupPosologyRouteList searchPosologyRouteByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId,
        @WebParam(name = "gender", targetNamespace = "urn:Vidal")
        Gender gender,
        @WebParam(name = "age", targetNamespace = "urn:Vidal")
        Float age,
        @WebParam(name = "weight", targetNamespace = "urn:Vidal")
        Float weight,
        @WebParam(name = "height", targetNamespace = "urn:Vidal")
        Integer height,
        @WebParam(name = "creatinClearance", targetNamespace = "urn:Vidal")
        Integer creatinClearance,
        @WebParam(name = "hepaticInsufficiency", targetNamespace = "urn:Vidal")
        HepaticInsufficiency hepaticInsufficiency,
        @WebParam(name = "indicationIds", targetNamespace = "urn:Vidal")
        ArrayOfInt indicationIds);

    /**
     * 
     * @param hepaticInsufficiency
     * @param indicationIds
     * @param productId
     * @param gender
     * @param creatinClearance
     * @param weight
     * @param age
     * @param height
     * @return
     *     returns com.whatever.PosologyService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "posologyRouteList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPosologyRouteByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPosologyRouteByProductId")
    @ResponseWrapper(localName = "searchPosologyRouteByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPosologyRouteByProductIdResponse")
    public ArrayOfRoute searchPosologyRouteByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId,
        @WebParam(name = "gender", targetNamespace = "urn:Vidal")
        Gender gender,
        @WebParam(name = "age", targetNamespace = "urn:Vidal")
        Float age,
        @WebParam(name = "weight", targetNamespace = "urn:Vidal")
        Float weight,
        @WebParam(name = "height", targetNamespace = "urn:Vidal")
        Integer height,
        @WebParam(name = "creatinClearance", targetNamespace = "urn:Vidal")
        Integer creatinClearance,
        @WebParam(name = "hepaticInsufficiency", targetNamespace = "urn:Vidal")
        HepaticInsufficiency hepaticInsufficiency,
        @WebParam(name = "indicationIds", targetNamespace = "urn:Vidal")
        ArrayOfInt indicationIds);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.PosologyService.CommonNameGroupPosologyUnitList
     */
    @WebMethod
    @WebResult(name = "prescriptionUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPrescriptionUnitsByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByCommonNameGroupId")
    @ResponseWrapper(localName = "searchPrescriptionUnitsByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByCommonNameGroupIdResponse")
    public CommonNameGroupPosologyUnitList searchPrescriptionUnitsByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param packageId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfPosologyUnit
     */
    @WebMethod
    @WebResult(name = "prescriptionUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPrescriptionUnitsByPackId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByPackId")
    @ResponseWrapper(localName = "searchPrescriptionUnitsByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByPackIdResponse")
    public ArrayOfPosologyUnit searchPrescriptionUnitsByPackId(
        @WebParam(name = "packageId", targetNamespace = "urn:Vidal")
        Integer packageId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfPosologyUnit
     */
    @WebMethod
    @WebResult(name = "prescriptionUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPrescriptionUnitsByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByProductId")
    @ResponseWrapper(localName = "searchPrescriptionUnitsByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByProductIdResponse")
    public ArrayOfPosologyUnit searchPrescriptionUnitsByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param ucdId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfPosologyUnit
     */
    @WebMethod
    @WebResult(name = "prescriptionUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPrescriptionUnitsByUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByUcdId")
    @ResponseWrapper(localName = "searchPrescriptionUnitsByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchPrescriptionUnitsByUcdIdResponse")
    public ArrayOfPosologyUnit searchPrescriptionUnitsByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        Integer ucdId);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRoutesByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByCommonNameGroupId")
    @ResponseWrapper(localName = "searchRoutesByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByCommonNameGroupIdResponse")
    public ArrayOfRoute searchRoutesByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        int commonNameGroupId);

    /**
     * 
     * @param packId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRoutesByPackId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByPackId")
    @ResponseWrapper(localName = "searchRoutesByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByPackIdResponse")
    public ArrayOfRoute searchRoutesByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        int packId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRoutesByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByProductId")
    @ResponseWrapper(localName = "searchRoutesByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByProductIdResponse")
    public ArrayOfRoute searchRoutesByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        int productId);

    /**
     * 
     * @param ucdId
     * @return
     *     returns com.whatever.PosologyService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRoutesByUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByUcdId")
    @ResponseWrapper(localName = "searchRoutesByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PosologyService.SearchRoutesByUcdIdResponse")
    public ArrayOfRoute searchRoutesByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        int ucdId);

}
