
package com.whatever.PackConservationService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PackConservationService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/PackConservationService.wsdl")
public class PackConservationService_Service
    extends Service
{

    private final static URL PACKCONSERVATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PACKCONSERVATIONSERVICE_EXCEPTION;
    private final static QName PACKCONSERVATIONSERVICE_QNAME = new QName("urn:Vidal", "PackConservationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/PackConservationService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PACKCONSERVATIONSERVICE_WSDL_LOCATION = url;
        PACKCONSERVATIONSERVICE_EXCEPTION = e;
    }

    public PackConservationService_Service() {
        super(__getWsdlLocation(), PACKCONSERVATIONSERVICE_QNAME);
    }

    public PackConservationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PackConservationService
     */
    @WebEndpoint(name = "PackConservationServiceHttpPort")
    public PackConservationService getPackConservationServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "PackConservationServiceHttpPort"), PackConservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PackConservationService
     */
    @WebEndpoint(name = "PackConservationServiceHttpPort")
    public PackConservationService getPackConservationServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "PackConservationServiceHttpPort"), PackConservationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PACKCONSERVATIONSERVICE_EXCEPTION!= null) {
            throw PACKCONSERVATIONSERVICE_EXCEPTION;
        }
        return PACKCONSERVATIONSERVICE_WSDL_LOCATION;
    }

}
