
package com.vidal.AtcService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AtcService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/AtcService.wsdl")
public class AtcService_Service
    extends Service
{

    private final static URL ATCSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATCSERVICE_EXCEPTION;
    private final static QName ATCSERVICE_QNAME = new QName("urn:Vidal", "AtcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/AtcService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATCSERVICE_WSDL_LOCATION = url;
        ATCSERVICE_EXCEPTION = e;
    }

    public AtcService_Service() {
        super(__getWsdlLocation(), ATCSERVICE_QNAME);
    }

    public AtcService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AtcService
     */
    @WebEndpoint(name = "AtcServiceHttpPort")
    public AtcService getAtcServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "AtcServiceHttpPort"), AtcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AtcService
     */
    @WebEndpoint(name = "AtcServiceHttpPort")
    public AtcService getAtcServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "AtcServiceHttpPort"), AtcService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATCSERVICE_EXCEPTION!= null) {
            throw ATCSERVICE_EXCEPTION;
        }
        return ATCSERVICE_WSDL_LOCATION;
    }

}
