
package com.vidal.AtcService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "atcService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AtcService {


    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.vidal.AtcService.PagedResultAtc
     */
    @WebMethod
    @WebResult(name = "pagedResultAtc", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllAtcs", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetAllAtcs")
    @ResponseWrapper(localName = "getAllAtcsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetAllAtcsResponse")
    public PagedResultAtc getAllAtcs(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param atcId
     * @return
     *     returns com.vidal.AtcService.ArrayOfAtc
     */
    @WebMethod
    @WebResult(name = "atcList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetChildrenResponse")
    public ArrayOfAtc getChildren(
        @WebParam(name = "atcId", targetNamespace = "urn:Vidal")
        Integer atcId);

    /**
     * 
     * @param atcId
     * @return
     *     returns com.vidal.AtcService.Atc
     */
    @WebMethod
    @WebResult(name = "atc", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetParentResponse")
    public Atc getParent(
        @WebParam(name = "atcId", targetNamespace = "urn:Vidal")
        Integer atcId);

    /**
     * 
     * @return
     *     returns com.vidal.AtcService.Atc
     */
    @WebMethod
    @WebResult(name = "atc", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.GetRootNodeResponse")
    public Atc getRootNode();

    /**
     * 
     * @param code
     * @return
     *     returns com.vidal.AtcService.ArrayOfAtc
     */
    @WebMethod
    @WebResult(name = "atcList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByCodeResponse")
    public ArrayOfAtc searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        String code);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.vidal.AtcService.ArrayOfAtc
     */
    @WebMethod
    @WebResult(name = "atcList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByCommonNameGroupIdResponse")
    public ArrayOfAtc searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param atcId
     * @return
     *     returns com.vidal.AtcService.Atc
     */
    @WebMethod
    @WebResult(name = "atc", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByIdResponse")
    public Atc searchById(
        @WebParam(name = "atcId", targetNamespace = "urn:Vidal")
        Integer atcId);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.AtcService.ArrayOfAtc
     */
    @WebMethod
    @WebResult(name = "atcList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByNameResponse")
    public ArrayOfAtc searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.AtcService.ArrayOfAtc
     */
    @WebMethod
    @WebResult(name = "atcList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AtcService.SearchByProductIdResponse")
    public ArrayOfAtc searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
