
package com.vidal.ApparatusService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "apparatusService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApparatusService {


    /**
     * 
     * @param apparatusId
     * @return
     *     returns com.vidal.ApparatusService.Apparatus
     */
    @WebMethod
    @WebResult(name = "apparatus", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchByIdResponse")
    public Apparatus searchById(
        @WebParam(name = "apparatusId", targetNamespace = "urn:Vidal")
        Integer apparatusId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.ApparatusService.ArrayOfApparatus
     */
    @WebMethod
    @WebResult(name = "apparatusList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchByProductIdResponse")
    public ArrayOfApparatus searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param sideEffectId
     * @return
     *     returns com.vidal.ApparatusService.Apparatus
     */
    @WebMethod
    @WebResult(name = "apparatus", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySideEffectId", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchBySideEffectId")
    @ResponseWrapper(localName = "searchBySideEffectIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchBySideEffectIdResponse")
    public Apparatus searchBySideEffectId(
        @WebParam(name = "sideEffectId", targetNamespace = "urn:Vidal")
        Integer sideEffectId);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.ApparatusService.ArrayOfApparatus
     */
    @WebMethod
    @WebResult(name = "apparatusList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySideEffectName", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchBySideEffectName")
    @ResponseWrapper(localName = "searchBySideEffectNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.ApparatusService.SearchBySideEffectNameResponse")
    public ArrayOfApparatus searchBySideEffectName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

}
