
package com.vidal.InteractionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "interactionService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InteractionService {


    /**
     * 
     * @param interactionId
     * @return
     *     returns com.vidal.InteractionService.Interaction
     */
    @WebMethod
    @WebResult(name = "interaction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByInteractionId", targetNamespace = "urn:Vidal", className = "com.vidal.InteractionService.SearchByInteractionId")
    @ResponseWrapper(localName = "searchByInteractionIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.InteractionService.SearchByInteractionIdResponse")
    public Interaction searchByInteractionId(
        @WebParam(name = "interactionId", targetNamespace = "urn:Vidal")
        Integer interactionId);

}
