
package com.vidal.PackConservationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "packConservationService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PackConservationService {


    /**
     * 
     * @param packId
     * @return
     *     returns com.vidal.PackConservationService.ArrayOfPackageConservation
     */
    @WebMethod
    @WebResult(name = "packConservationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.vidal.PackConservationService.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.PackConservationService.SearchByPackIdResponse")
    public ArrayOfPackageConservation searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

}
