
package com.whatever.CommonNameGroupService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CommonNameGroupService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/CommonNameGroupService.wsdl")
public class CommonNameGroupService_Service
    extends Service
{

    private final static URL COMMONNAMEGROUPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMONNAMEGROUPSERVICE_EXCEPTION;
    private final static QName COMMONNAMEGROUPSERVICE_QNAME = new QName("urn:Vidal", "CommonNameGroupService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/CommonNameGroupService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMONNAMEGROUPSERVICE_WSDL_LOCATION = url;
        COMMONNAMEGROUPSERVICE_EXCEPTION = e;
    }

    public CommonNameGroupService_Service() {
        super(__getWsdlLocation(), COMMONNAMEGROUPSERVICE_QNAME);
    }

    public CommonNameGroupService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CommonNameGroupService
     */
    @WebEndpoint(name = "CommonNameGroupServiceHttpPort")
    public CommonNameGroupService getCommonNameGroupServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "CommonNameGroupServiceHttpPort"), CommonNameGroupService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonNameGroupService
     */
    @WebEndpoint(name = "CommonNameGroupServiceHttpPort")
    public CommonNameGroupService getCommonNameGroupServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "CommonNameGroupServiceHttpPort"), CommonNameGroupService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONNAMEGROUPSERVICE_EXCEPTION!= null) {
            throw COMMONNAMEGROUPSERVICE_EXCEPTION;
        }
        return COMMONNAMEGROUPSERVICE_WSDL_LOCATION;
    }

}
