
package com.whatever.CommonNameGroupService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "commonNameGroupService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonNameGroupService {


    /**
     * 
     * @param pageNumber
     * @param name
     * @param pageSize
     * @param aggregates
     * @return
     *     returns com.whatever.CommonNameGroupService.PagedResultCommonNameGroupFull
     */
    @WebMethod
    @WebResult(name = "pagedResultCommonNameGroupFull", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllCommonNameGroupFulls", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetAllCommonNameGroupFulls")
    @ResponseWrapper(localName = "getAllCommonNameGroupFullsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetAllCommonNameGroupFullsResponse")
    public PagedResultCommonNameGroupFull getAllCommonNameGroupFulls(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        ArrayOfAggregate aggregates,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber);

    /**
     * 
     * @param commonNameGroupIds
     * @param aggregates
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroupFull
     */
    @WebMethod
    @WebResult(name = "commonNameGroupFullList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCommonNameGroupFullByIds", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetCommonNameGroupFullByIds")
    @ResponseWrapper(localName = "getCommonNameGroupFullByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetCommonNameGroupFullByIdsResponse")
    public ArrayOfCommonNameGroupFull getCommonNameGroupFullByIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        ArrayOfInt commonNameGroupIds,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        ArrayOfAggregate aggregates);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.CommonNameGroupService.GalenicForm
     */
    @WebMethod
    @WebResult(name = "galenicForm", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getGalenicForm", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetGalenicForm")
    @ResponseWrapper(localName = "getGalenicFormResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetGalenicFormResponse")
    public GalenicForm getGalenicForm(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfConvertibleUnit
     */
    @WebMethod
    @WebResult(name = "convertibleUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getUnits", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetUnits")
    @ResponseWrapper(localName = "getUnitsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.GetUnitsResponse")
    public ArrayOfConvertibleUnit getUnits(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        int commonNameGroupId);

    /**
     * 
     * @param moleculeIds
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByActivePrincipleIds", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByActivePrincipleIds")
    @ResponseWrapper(localName = "searchByActivePrincipleIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByActivePrincipleIdsResponse")
    public ArrayOfCommonNameGroup searchByActivePrincipleIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt moleculeIds);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param aldId
     * @return
     *     returns com.whatever.CommonNameGroupService.PagedResultCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "pagedResultCommonNameGroupByAld", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAldId", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByAldId")
    @ResponseWrapper(localName = "searchByAldIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByAldIdResponse")
    public PagedResultCommonNameGroup searchByAldId(
        @WebParam(name = "aldId", targetNamespace = "urn:Vidal")
        Integer aldId,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param atcIds
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAtcIds", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByAtcIds")
    @ResponseWrapper(localName = "searchByAtcIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByAtcIdsResponse")
    public ArrayOfCommonNameGroup searchByAtcIds(
        @WebParam(name = "atcIds", targetNamespace = "urn:Vidal")
        ArrayOfInt atcIds);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.CommonNameGroupService.CommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIdResponse")
    public CommonNameGroup searchById(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param commonNameGroupIds
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIdsResponse")
    public ArrayOfCommonNameGroup searchByIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        ArrayOfInt commonNameGroupIds);

    /**
     * 
     * @param indicationLESCode
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.CommonNameGroupService.PagedResultCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "pagedResultCommonNameGroupByIndicationLESCode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationLESCode", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIndicationLESCode")
    @ResponseWrapper(localName = "searchByIndicationLESCodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIndicationLESCodeResponse")
    public PagedResultCommonNameGroup searchByIndicationLESCode(
        @WebParam(name = "indicationLESCode", targetNamespace = "urn:Vidal")
        String indicationLESCode,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param operatorType
     * @param indicators
     * @return
     *     returns com.whatever.CommonNameGroupService.PagedResultCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "pagedResultCommonNameGroupByIndicators", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicatorIds", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIndicatorIds")
    @ResponseWrapper(localName = "searchByIndicatorIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByIndicatorIdsResponse")
    public PagedResultCommonNameGroup searchByIndicatorIds(
        @WebParam(name = "indicators", targetNamespace = "urn:Vidal")
        ArrayOfInt indicators,
        @WebParam(name = "operatorType", targetNamespace = "urn:Vidal")
        SetOperatorType operatorType,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param medicaBaseCodes
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMedicaBaseCodes", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByMedicaBaseCodes")
    @ResponseWrapper(localName = "searchByMedicaBaseCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByMedicaBaseCodesResponse")
    public ArrayOfCommonNameGroup searchByMedicaBaseCodes(
        @WebParam(name = "medicaBaseCodes", targetNamespace = "urn:Vidal")
        ArrayOfString medicaBaseCodes);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByNameResponse")
    public ArrayOfCommonNameGroup searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param pageNumber
     * @param otherIndicationCode
     * @param pageSize
     * @return
     *     returns com.whatever.CommonNameGroupService.PagedResultCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "pagedResultCommonNameGroupByOtherIndicationCode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByOtherIndicationCode", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByOtherIndicationCode")
    @ResponseWrapper(localName = "searchByOtherIndicationCodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByOtherIndicationCodeResponse")
    public PagedResultCommonNameGroup searchByOtherIndicationCode(
        @WebParam(name = "otherIndicationCode", targetNamespace = "urn:Vidal")
        String otherIndicationCode,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param packId
     * @return
     *     returns com.whatever.CommonNameGroupService.CommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByPackIdResponse")
    public CommonNameGroup searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.CommonNameGroupService.CommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByProductIdResponse")
    public CommonNameGroup searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param ucdId
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroup
     */
    @WebMethod
    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByUcdId")
    @ResponseWrapper(localName = "searchByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchByUcdIdResponse")
    public ArrayOfCommonNameGroup searchByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        Integer ucdId);

    /**
     * 
     * @param commonNameGroupIds
     * @return
     *     returns com.whatever.CommonNameGroupService.ArrayOfCommonNameGroupIndicators
     */
    @WebMethod
    @WebResult(name = "commonNameGroupIndicatorsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCommonNameGroupIndicatorsByCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchCommonNameGroupIndicatorsByCommonNameGroupIds")
    @ResponseWrapper(localName = "searchCommonNameGroupIndicatorsByCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CommonNameGroupService.SearchCommonNameGroupIndicatorsByCommonNameGroupIdsResponse")
    public ArrayOfCommonNameGroupIndicators searchCommonNameGroupIndicatorsByCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        ArrayOfInt commonNameGroupIds);

}
