
package com.whatever.VidalService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "vidalService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VidalService {


    /**
     * 
     * @param vidalId
     * @return
     *     returns com.whatever.VidalService.ArrayOfVidal
     */
    @WebMethod
    @WebResult(name = "vidalList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.GetChildrenResponse")
    public ArrayOfVidal getChildren(
        @WebParam(name = "vidalId", targetNamespace = "urn:Vidal")
        Integer vidalId);

    /**
     * 
     * @param vidalId
     * @return
     *     returns com.whatever.VidalService.Vidal
     */
    @WebMethod
    @WebResult(name = "vidal", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.GetParentResponse")
    public Vidal getParent(
        @WebParam(name = "vidalId", targetNamespace = "urn:Vidal")
        Integer vidalId);

    /**
     * 
     * @return
     *     returns com.whatever.VidalService.Vidal
     */
    @WebMethod
    @WebResult(name = "vidal", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.GetRootNodeResponse")
    public Vidal getRootNode();

    /**
     * 
     * @param vidalId
     * @return
     *     returns com.whatever.VidalService.Vidal
     */
    @WebMethod
    @WebResult(name = "vidal", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.SearchByIdResponse")
    public Vidal searchById(
        @WebParam(name = "vidalId", targetNamespace = "urn:Vidal")
        Integer vidalId);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.VidalService.ArrayOfVidal
     */
    @WebMethod
    @WebResult(name = "vidalList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.SearchByNameResponse")
    public ArrayOfVidal searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.VidalService.ArrayOfVidal
     */
    @WebMethod
    @WebResult(name = "vidalList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.VidalService.SearchByProductIdResponse")
    public ArrayOfVidal searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
