
package com.whatever.Cim10Service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Cim10Service", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/Cim10Service.wsdl")
public class Cim10Service_Service
    extends Service
{

    private final static URL CIM10SERVICE_WSDL_LOCATION;
    private final static WebServiceException CIM10SERVICE_EXCEPTION;
    private final static QName CIM10SERVICE_QNAME = new QName("urn:Vidal", "Cim10Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/Cim10Service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CIM10SERVICE_WSDL_LOCATION = url;
        CIM10SERVICE_EXCEPTION = e;
    }

    public Cim10Service_Service() {
        super(__getWsdlLocation(), CIM10SERVICE_QNAME);
    }

    public Cim10Service_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Cim10Service
     */
    @WebEndpoint(name = "Cim10ServiceHttpPort")
    public Cim10Service getCim10ServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "Cim10ServiceHttpPort"), Cim10Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cim10Service
     */
    @WebEndpoint(name = "Cim10ServiceHttpPort")
    public Cim10Service getCim10ServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "Cim10ServiceHttpPort"), Cim10Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CIM10SERVICE_EXCEPTION!= null) {
            throw CIM10SERVICE_EXCEPTION;
        }
        return CIM10SERVICE_WSDL_LOCATION;
    }

}
