
package com.whatever.FoodInteractionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "foodInteractionService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FoodInteractionService {


    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.FoodInteractionService.ArrayOfFoodInteractionCommentCouple
     */
    @WebMethod
    @WebResult(name = "foodInteractionCommentCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByCommonNameGroupIdResponse")
    public ArrayOfFoodInteractionCommentCouple searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param foodInteractionId
     * @return
     *     returns com.whatever.FoodInteractionService.FoodInteraction
     */
    @WebMethod
    @WebResult(name = "foodInteraction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByIdResponse")
    public FoodInteraction searchById(
        @WebParam(name = "foodInteractionId", targetNamespace = "urn:Vidal")
        Integer foodInteractionId);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.FoodInteractionService.ArrayOfFoodInteraction
     */
    @WebMethod
    @WebResult(name = "foodInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByNameResponse")
    public ArrayOfFoodInteraction searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.FoodInteractionService.ArrayOfFoodInteractionCommentCouple
     */
    @WebMethod
    @WebResult(name = "foodInteractionCommentCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.FoodInteractionService.SearchByProductIdResponse")
    public ArrayOfFoodInteractionCommentCouple searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
