
package com.vidal.AdministrationRouteService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "administrationRouteService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdministrationRouteService {


    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.vidal.AdministrationRouteService.PagedResultRoute
     */
    @WebMethod
    @WebResult(name = "pagedResultRoute", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllRoutes", targetNamespace = "urn:Vidal", className = "com.vidal.AdministrationRouteService.GetAllRoutes")
    @ResponseWrapper(localName = "getAllRoutesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AdministrationRouteService.GetAllRoutesResponse")
    public PagedResultRoute getAllRoutes(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param routeIds
     * @return
     *     returns com.vidal.AdministrationRouteService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.vidal.AdministrationRouteService.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AdministrationRouteService.SearchByIdsResponse")
    public ArrayOfRoute searchByIds(
        @WebParam(name = "routeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt routeIds);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.AdministrationRouteService.ArrayOfRoute
     */
    @WebMethod
    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.AdministrationRouteService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.AdministrationRouteService.SearchByNameResponse")
    public ArrayOfRoute searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

}
