
package com.whatever.EphmraService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EphmraService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/EphmraService.wsdl")
public class EphmraService_Service
    extends Service
{

    private final static URL EPHMRASERVICE_WSDL_LOCATION;
    private final static WebServiceException EPHMRASERVICE_EXCEPTION;
    private final static QName EPHMRASERVICE_QNAME = new QName("urn:Vidal", "EphmraService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/EphmraService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPHMRASERVICE_WSDL_LOCATION = url;
        EPHMRASERVICE_EXCEPTION = e;
    }

    public EphmraService_Service() {
        super(__getWsdlLocation(), EPHMRASERVICE_QNAME);
    }

    public EphmraService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns EphmraService
     */
    @WebEndpoint(name = "EphmraServiceHttpPort")
    public EphmraService getEphmraServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "EphmraServiceHttpPort"), EphmraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EphmraService
     */
    @WebEndpoint(name = "EphmraServiceHttpPort")
    public EphmraService getEphmraServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "EphmraServiceHttpPort"), EphmraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPHMRASERVICE_EXCEPTION!= null) {
            throw EPHMRASERVICE_EXCEPTION;
        }
        return EPHMRASERVICE_WSDL_LOCATION;
    }

}
