
package com.vidal.EphmraService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ephmraService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EphmraService {


    /**
     * 
     * @param ephmraId
     * @return
     *     returns com.vidal.EphmraService.ArrayOfEphmra
     */
    @WebMethod
    @WebResult(name = "ephmraList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.GetChildrenResponse")
    public ArrayOfEphmra getChildren(
        @WebParam(name = "ephmraId", targetNamespace = "urn:Vidal")
        Integer ephmraId);

    /**
     * 
     * @param ephmraId
     * @return
     *     returns com.vidal.EphmraService.Ephmra
     */
    @WebMethod
    @WebResult(name = "ephmra", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.GetParentResponse")
    public Ephmra getParent(
        @WebParam(name = "ephmraId", targetNamespace = "urn:Vidal")
        Integer ephmraId);

    /**
     * 
     * @return
     *     returns com.vidal.EphmraService.Ephmra
     */
    @WebMethod
    @WebResult(name = "ephmra", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.GetRootNodeResponse")
    public Ephmra getRootNode();

    /**
     * 
     * @param code
     * @return
     *     returns com.vidal.EphmraService.ArrayOfEphmra
     */
    @WebMethod
    @WebResult(name = "ephmraList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByCodeResponse")
    public ArrayOfEphmra searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        String code);

    /**
     * 
     * @param ephmraId
     * @return
     *     returns com.vidal.EphmraService.Ephmra
     */
    @WebMethod
    @WebResult(name = "ephmra", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByIdResponse")
    public Ephmra searchById(
        @WebParam(name = "ephmraId", targetNamespace = "urn:Vidal")
        Integer ephmraId);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.EphmraService.ArrayOfEphmra
     */
    @WebMethod
    @WebResult(name = "ephmraList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByNameResponse")
    public ArrayOfEphmra searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param packId
     * @return
     *     returns com.vidal.EphmraService.ArrayOfEphmra
     */
    @WebMethod
    @WebResult(name = "ephmraList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByPackIdResponse")
    public ArrayOfEphmra searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.EphmraService.ArrayOfEphmra
     */
    @WebMethod
    @WebResult(name = "ephmraList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.EphmraService.SearchByProductIdResponse")
    public ArrayOfEphmra searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
