
package com.vidal.SmrService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "smrService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmrService {


    /**
     * 
     * @param productId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "smrAsmrAsHTML", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getSmrAsmrAsHTML", targetNamespace = "urn:Vidal", className = "com.vidal.SmrService.GetSmrAsmrAsHTML")
    @ResponseWrapper(localName = "getSmrAsmrAsHTMLResponse", targetNamespace = "urn:Vidal", className = "com.vidal.SmrService.GetSmrAsmrAsHTMLResponse")
    public String getSmrAsmrAsHTML(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.SmrService.ArrayOfSmr
     */
    @WebMethod
    @WebResult(name = "smrList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.SmrService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.SmrService.SearchByProductIdResponse")
    public ArrayOfSmr searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
