
package com.vidal.VidalService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VidalService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/VidalService.wsdl")
public class VidalService_Service
    extends Service
{

    private final static URL VIDALSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIDALSERVICE_EXCEPTION;
    private final static QName VIDALSERVICE_QNAME = new QName("urn:Vidal", "VidalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/VidalService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIDALSERVICE_WSDL_LOCATION = url;
        VIDALSERVICE_EXCEPTION = e;
    }

    public VidalService_Service() {
        super(__getWsdlLocation(), VIDALSERVICE_QNAME);
    }

    public VidalService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns VidalService
     */
    @WebEndpoint(name = "VidalServiceHttpPort")
    public VidalService getVidalServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "VidalServiceHttpPort"), VidalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidalService
     */
    @WebEndpoint(name = "VidalServiceHttpPort")
    public VidalService getVidalServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "VidalServiceHttpPort"), VidalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIDALSERVICE_EXCEPTION!= null) {
            throw VIDALSERVICE_EXCEPTION;
        }
        return VIDALSERVICE_WSDL_LOCATION;
    }

}
