
package com.whatever.CodingService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CodingService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/CodingService.wsdl")
public class CodingService_Service
    extends Service
{

    private final static URL CODINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException CODINGSERVICE_EXCEPTION;
    private final static QName CODINGSERVICE_QNAME = new QName("urn:Vidal", "CodingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/CodingService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CODINGSERVICE_WSDL_LOCATION = url;
        CODINGSERVICE_EXCEPTION = e;
    }

    public CodingService_Service() {
        super(__getWsdlLocation(), CODINGSERVICE_QNAME);
    }

    public CodingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CodingService
     */
    @WebEndpoint(name = "CodingServiceHttpPort")
    public CodingService getCodingServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "CodingServiceHttpPort"), CodingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CodingService
     */
    @WebEndpoint(name = "CodingServiceHttpPort")
    public CodingService getCodingServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "CodingServiceHttpPort"), CodingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CODINGSERVICE_EXCEPTION!= null) {
            throw CODINGSERVICE_EXCEPTION;
        }
        return CODINGSERVICE_WSDL_LOCATION;
    }

}
