
package com.whatever.PackService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "packService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PackService {


    /**
     * 
     * @param types
     * @param pageNumber
     * @param pageSize
     * @param marketStatuses
     * @param packApiFilter
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPack", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllPackages", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetAllPackages")
    @ResponseWrapper(localName = "getAllPackagesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetAllPackagesResponse")
    public PagedResultPack getAllPackages(
        @WebParam(name = "packApiFilter", targetNamespace = "urn:Vidal")
        PackApiFilter packApiFilter,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfProductType types,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param aggregates
     * @param packageIds
     * @return
     *     returns com.whatever.PackService.ArrayOfPackFull
     */
    @WebMethod
    @WebResult(name = "packFullList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPackFullByIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetPackFullByIds")
    @ResponseWrapper(localName = "getPackFullByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetPackFullByIdsResponse")
    public ArrayOfPackFull getPackFullByIds(
        @WebParam(name = "packageIds", targetNamespace = "urn:Vidal")
        ArrayOfInt packageIds,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        ArrayOfAggregate aggregates);

    /**
     * 
     * @param reimbursementScheduleFilter
     * @param packIds
     * @return
     *     returns com.whatever.PackService.ArrayOfPackageReimbursementCouple
     */
    @WebMethod
    @WebResult(name = "packageReimbursementCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getReimbursementSchedule", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetReimbursementSchedule")
    @ResponseWrapper(localName = "getReimbursementScheduleResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetReimbursementScheduleResponse")
    public ArrayOfPackageReimbursementCouple getReimbursementSchedule(
        @WebParam(name = "packIds", targetNamespace = "urn:Vidal")
        ArrayOfInt packIds,
        @WebParam(name = "reimbursementScheduleFilter", targetNamespace = "urn:Vidal")
        ReimbursementScheduleFilter reimbursementScheduleFilter);

    /**
     * 
     * @param packId
     * @return
     *     returns com.whatever.PackService.ArrayOfConvertibleUnit
     */
    @WebMethod
    @WebResult(name = "convertibleUnitList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getUnits", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetUnits")
    @ResponseWrapper(localName = "getUnitsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.GetUnitsResponse")
    public ArrayOfConvertibleUnit getUnits(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param aldId
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPacksByAld", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAldId", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByAldId")
    @ResponseWrapper(localName = "searchByAldIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByAldIdResponse")
    public PagedResultPack searchByAldId(
        @WebParam(name = "aldId", targetNamespace = "urn:Vidal")
        Integer aldId,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param cips
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCodes", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByCodes")
    @ResponseWrapper(localName = "searchByCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByCodesResponse")
    public ArrayOfPack searchByCodes(
        @WebParam(name = "cips", targetNamespace = "urn:Vidal")
        ArrayOfString cips);

    /**
     * 
     * @param companyId
     * @param type
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCompanyIdAndType", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByCompanyIdAndType")
    @ResponseWrapper(localName = "searchByCompanyIdAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByCompanyIdAndTypeResponse")
    public ArrayOfPack searchByCompanyIdAndType(
        @WebParam(name = "companyId", targetNamespace = "urn:Vidal")
        Integer companyId,
        @WebParam(name = "type", targetNamespace = "urn:Vidal")
        CompanyType type);

    /**
     * 
     * @param ephmraId
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByEphmraId", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByEphmraId")
    @ResponseWrapper(localName = "searchByEphmraIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByEphmraIdResponse")
    public ArrayOfPack searchByEphmraId(
        @WebParam(name = "ephmraId", targetNamespace = "urn:Vidal")
        Integer ephmraId);

    /**
     * 
     * @param packId
     * @return
     *     returns com.whatever.PackService.Pack
     */
    @WebMethod
    @WebResult(name = "pack", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIdResponse")
    public Pack searchById(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId);

    /**
     * 
     * @param indicationIds
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIndicationIds")
    @ResponseWrapper(localName = "searchByIndicationIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIndicationIdsResponse")
    public ArrayOfPack searchByIndicationIds(
        @WebParam(name = "indicationIds", targetNamespace = "urn:Vidal")
        ArrayOfInt indicationIds);

    /**
     * 
     * @param indicationLESCode
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPackByIndicationLESCode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationLESCode", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIndicationLESCode")
    @ResponseWrapper(localName = "searchByIndicationLESCodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIndicationLESCodeResponse")
    public PagedResultPack searchByIndicationLESCode(
        @WebParam(name = "indicationLESCode", targetNamespace = "urn:Vidal")
        String indicationLESCode,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param operatorType
     * @param indicators
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPackByIndicators", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicatorIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIndicatorIds")
    @ResponseWrapper(localName = "searchByIndicatorIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByIndicatorIdsResponse")
    public PagedResultPack searchByIndicatorIds(
        @WebParam(name = "indicators", targetNamespace = "urn:Vidal")
        ArrayOfInt indicators,
        @WebParam(name = "operatorType", targetNamespace = "urn:Vidal")
        SetOperatorType operatorType,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param pageSize
     * @param lpprIds
     * @return
     *     returns com.whatever.PackService.PagedResultPackLpprCouple
     */
    @WebMethod
    @WebResult(name = "PagedResultPackLpprCouple", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByLpprIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByLpprIds")
    @ResponseWrapper(localName = "searchByLpprIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByLpprIdsResponse")
    public PagedResultPackLpprCouple searchByLpprIds(
        @WebParam(name = "lpprIds", targetNamespace = "urn:Vidal")
        ArrayOfInt lpprIds,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param types
     * @param pageNumber
     * @param name
     * @param pageSize
     * @param marketStatuses
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPack", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameWithPagedResult", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByNameWithPagedResult")
    @ResponseWrapper(localName = "searchByNameWithPagedResultResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByNameWithPagedResultResponse")
    public PagedResultPack searchByNameWithPagedResult(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        ArrayOfProductType types,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param otherIndicationCode
     * @param pageSize
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPackByOtherIndicationCode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByOtherIndicationCode", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByOtherIndicationCode")
    @ResponseWrapper(localName = "searchByOtherIndicationCodeResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByOtherIndicationCodeResponse")
    public PagedResultPack searchByOtherIndicationCode(
        @WebParam(name = "otherIndicationCode", targetNamespace = "urn:Vidal")
        String otherIndicationCode,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param pageNumber
     * @param productIds
     * @param pageSize
     * @return
     *     returns com.whatever.PackService.PagedResultPack
     */
    @WebMethod
    @WebResult(name = "pagedResultPack", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByProductIds")
    @ResponseWrapper(localName = "searchByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByProductIdsResponse")
    public PagedResultPack searchByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param productRangeIds
     * @return
     *     returns com.whatever.PackService.ArrayOfProductRangePackCouple
     */
    @WebMethod
    @WebResult(name = "ProductRangePackCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductRangeIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByProductRangeIds")
    @ResponseWrapper(localName = "searchByProductRangeIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByProductRangeIdsResponse")
    public ArrayOfProductRangePackCouple searchByProductRangeIds(
        @WebParam(name = "productRangeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productRangeIds);

    /**
     * 
     * @param codes
     * @param searchPackCode
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByTypedCodes", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByTypedCodes")
    @ResponseWrapper(localName = "searchByTypedCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByTypedCodesResponse")
    public ArrayOfPack searchByTypedCodes(
        @WebParam(name = "searchPackCode", targetNamespace = "urn:Vidal")
        SearchPackCode searchPackCode,
        @WebParam(name = "codes", targetNamespace = "urn:Vidal")
        ArrayOfString codes);

    /**
     * 
     * @param ucdId
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByUcdId", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByUcdId")
    @ResponseWrapper(localName = "searchByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchByUcdIdResponse")
    public ArrayOfPack searchByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        Integer ucdId);

    /**
     * 
     * @return
     *     returns com.whatever.PackService.ArrayOfPack
     */
    @WebMethod
    @WebResult(name = "packList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNewlyAvailablePacks", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchNewlyAvailablePacks")
    @ResponseWrapper(localName = "searchNewlyAvailablePacksResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchNewlyAvailablePacksResponse")
    public ArrayOfPack searchNewlyAvailablePacks();

    /**
     * 
     * @param packIds
     * @return
     *     returns com.whatever.PackService.ArrayOfPackIndicators
     */
    @WebMethod
    @WebResult(name = "packIndicatorsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchPackIndicatorsByPackIds", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchPackIndicatorsByPackIds")
    @ResponseWrapper(localName = "searchPackIndicatorsByPackIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchPackIndicatorsByPackIdsResponse")
    public ArrayOfPackIndicators searchPackIndicatorsByPackIds(
        @WebParam(name = "packIds", targetNamespace = "urn:Vidal")
        ArrayOfInt packIds);

    /**
     * 
     * @param packId
     * @param indicationId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "refundingRate", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRefundingRateByIndicationId", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchRefundingRateByIndicationId")
    @ResponseWrapper(localName = "searchRefundingRateByIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.PackService.SearchRefundingRateByIndicationIdResponse")
    public String searchRefundingRateByIndicationId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        Integer packId,
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        Integer indicationId);

}
