
package com.vidal.CispService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "cispService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CispService {


    /**
     * 
     * @param cispId
     * @return
     *     returns com.vidal.CispService.ArrayOfCisp
     */
    @WebMethod
    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.GetChildrenResponse")
    public ArrayOfCisp getChildren(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        Integer cispId);

    /**
     * 
     * @param cispId
     * @return
     *     returns com.vidal.CispService.Cisp
     */
    @WebMethod
    @WebResult(name = "cisp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.GetParentResponse")
    public Cisp getParent(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        Integer cispId);

    /**
     * 
     * @return
     *     returns com.vidal.CispService.Cisp
     */
    @WebMethod
    @WebResult(name = "cisp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.GetRootNodeResponse")
    public Cisp getRootNode();

    /**
     * 
     * @param code
     * @return
     *     returns com.vidal.CispService.ArrayOfCisp
     */
    @WebMethod
    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByCodeResponse")
    public ArrayOfCisp searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        String code);

    /**
     * 
     * @param cispId
     * @return
     *     returns com.vidal.CispService.Cisp
     */
    @WebMethod
    @WebResult(name = "cisp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByIdResponse")
    public Cisp searchById(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        Integer cispId);

    /**
     * 
     * @param indicationGroupId
     * @return
     *     returns com.vidal.CispService.ArrayOfCisp
     */
    @WebMethod
    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByIndicationGroupIdResponse")
    public ArrayOfCisp searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        Integer indicationGroupId);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.CispService.ArrayOfCisp
     */
    @WebMethod
    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.CispService.SearchByNameResponse")
    public ArrayOfCisp searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

}
