
package com.whatever.IndicationGroupService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "indicationGroupService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IndicationGroupService {


    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroupScore
     */
    @WebMethod
    @WebResult(name = "indicationGroupScoreList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "postIndexingHealthTerminologyByProductIds", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.PostIndexingHealthTerminologyByProductIds")
    @ResponseWrapper(localName = "postIndexingHealthTerminologyByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.PostIndexingHealthTerminologyByProductIdsResponse")
    public ArrayOfIndicationGroupScore postIndexingHealthTerminologyByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

    /**
     * 
     * @param cim10Id
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCim10Id", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByCim10Id")
    @ResponseWrapper(localName = "searchByCim10IdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByCim10IdResponse")
    public ArrayOfIndicationGroup searchByCim10Id(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        Integer cim10Id);

    /**
     * 
     * @param cispId
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCispId", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByCispId")
    @ResponseWrapper(localName = "searchByCispIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByCispIdResponse")
    public ArrayOfIndicationGroup searchByCispId(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        Integer cispId);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByCommonNameGroupIdResponse")
    public ArrayOfIndicationGroup searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param indicationGroupId
     * @return
     *     returns com.whatever.IndicationGroupService.IndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByIdResponse")
    public IndicationGroup searchById(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        Integer indicationGroupId);

    /**
     * 
     * @param indicationId
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationId", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByIndicationId")
    @ResponseWrapper(localName = "searchByIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByIndicationIdResponse")
    public ArrayOfIndicationGroup searchByIndicationId(
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        Integer indicationId);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByNameResponse")
    public ArrayOfIndicationGroup searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchByProductIdResponse")
    public ArrayOfIndicationGroup searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

    /**
     * 
     * @param sfmgId
     * @return
     *     returns com.whatever.IndicationGroupService.ArrayOfIndicationGroup
     */
    @WebMethod
    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySfmgId", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchBySfmgId")
    @ResponseWrapper(localName = "searchBySfmgIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.IndicationGroupService.SearchBySfmgIdResponse")
    public ArrayOfIndicationGroup searchBySfmgId(
        @WebParam(name = "sfmgId", targetNamespace = "urn:Vidal")
        Integer sfmgId);

}
