
package com.whatever.CompositionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "compositionService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompositionService {


    /**
     * 
     * @param commonNameGroupIds
     * @return
     *     returns com.whatever.CompositionService.ArrayOfCommonNameGroupComposition
     */
    @WebMethod
    @WebResult(name = "commonNameGroupCompositionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "com.whatever.CompositionService.SearchByCommonNameGroupIds")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CompositionService.SearchByCommonNameGroupIdsResponse")
    public ArrayOfCommonNameGroupComposition searchByCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        ArrayOfInt commonNameGroupIds);

    /**
     * 
     * @param productId
     * @param substanceTypes
     * @return
     *     returns com.whatever.CompositionService.ArrayOfItemCompositionsCouple
     */
    @WebMethod
    @WebResult(name = "itemCompositionsCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCompositionsByProduct", targetNamespace = "urn:Vidal", className = "com.whatever.CompositionService.SearchCompositionsByProduct")
    @ResponseWrapper(localName = "searchCompositionsByProductResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CompositionService.SearchCompositionsByProductResponse")
    public ArrayOfItemCompositionsCouple searchCompositionsByProduct(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId,
        @WebParam(name = "substanceTypes", targetNamespace = "urn:Vidal")
        ArrayOfSubstanceType substanceTypes);

    /**
     * 
     * @param substanceTypes
     * @param ucdId
     * @return
     *     returns com.whatever.CompositionService.ArrayOfItemCompositionsCouple
     */
    @WebMethod
    @WebResult(name = "itemCompositionsCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCompositionsByUcdIdAndSubstanceTypes", targetNamespace = "urn:Vidal", className = "com.whatever.CompositionService.SearchCompositionsByUcdIdAndSubstanceTypes")
    @ResponseWrapper(localName = "searchCompositionsByUcdIdAndSubstanceTypesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.CompositionService.SearchCompositionsByUcdIdAndSubstanceTypesResponse")
    public ArrayOfItemCompositionsCouple searchCompositionsByUcdIdAndSubstanceTypes(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        Integer ucdId,
        @WebParam(name = "substanceTypes", targetNamespace = "urn:Vidal")
        ArrayOfSubstanceType substanceTypes);

}
