
package com.whatever.RedundantInteractionService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "redundantInteractionService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RedundantInteractionService {


    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.RedundantInteractionService.ArrayOfRedundantInteractionCouple
     */
    @WebMethod
    @WebResult(name = "redundantInteractionCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRedundantInteractionByProductIds", targetNamespace = "urn:Vidal", className = "com.whatever.RedundantInteractionService.SearchRedundantInteractionByProductIds")
    @ResponseWrapper(localName = "searchRedundantInteractionByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.RedundantInteractionService.SearchRedundantInteractionByProductIdsResponse")
    public ArrayOfRedundantInteractionCouple searchRedundantInteractionByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

    /**
     * 
     * @param commonNameGroupIds
     * @return
     *     returns com.whatever.RedundantInteractionService.ArrayOfRedundantInteractionCommonNameGroupCouple
     */
    @WebMethod
    @WebResult(name = "redundantInteractionCommonNameGroupCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRedundantInteractionByCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "com.whatever.RedundantInteractionService.SearchRedundantInteractionByCommonNameGroupIds")
    @ResponseWrapper(localName = "searchRedundantInteractionByCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.RedundantInteractionService.SearchRedundantInteractionByCommonNameGroupIdsResponse")
    public ArrayOfRedundantInteractionCommonNameGroupCouple searchRedundantInteractionByCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        ArrayOfInt commonNameGroupIds);

    /**
     * 
     * @param productIds
     * @return
     *     returns com.whatever.RedundantInteractionService.ArrayOfRedundantInteractionCouple
     */
    @WebMethod
    @WebResult(name = "redundantInteractionCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRedundantInteraction", targetNamespace = "urn:Vidal", className = "com.whatever.RedundantInteractionService.SearchRedundantInteraction")
    @ResponseWrapper(localName = "searchRedundantInteractionResponse", targetNamespace = "urn:Vidal", className = "com.whatever.RedundantInteractionService.SearchRedundantInteractionResponse")
    public ArrayOfRedundantInteractionCouple searchRedundantInteraction(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        ArrayOfInt productIds);

}
