
package com.whatever.AldService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "aldService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AldService {


    /**
     * 
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllAlds", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.GetAllAlds")
    @ResponseWrapper(localName = "getAllAldsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.GetAllAldsResponse")
    public ArrayOfAld getAllAlds();

    /**
     * 
     * @param aldId
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.GetChildrenResponse")
    public ArrayOfAld getChildren(
        @WebParam(name = "aldId", targetNamespace = "urn:Vidal")
        Integer aldId);

    /**
     * 
     * @param cim10Id
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCim10Id", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByCim10Id")
    @ResponseWrapper(localName = "searchByCim10IdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByCim10IdResponse")
    public ArrayOfAld searchByCim10Id(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        int cim10Id);

    /**
     * 
     * @param codes
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCodes", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByCodes")
    @ResponseWrapper(localName = "searchByCodesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByCodesResponse")
    public ArrayOfAld searchByCodes(
        @WebParam(name = "codes", targetNamespace = "urn:Vidal")
        ArrayOfString codes);

    /**
     * 
     * @param cngId
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByCommonNameGroupIdResponse")
    public ArrayOfAld searchByCommonNameGroupId(
        @WebParam(name = "cngId", targetNamespace = "urn:Vidal")
        int cngId);

    /**
     * 
     * @param aldId
     * @return
     *     returns com.whatever.AldService.Ald
     */
    @WebMethod
    @WebResult(name = "ald", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByIdResponse")
    public Ald searchById(
        @WebParam(name = "aldId", targetNamespace = "urn:Vidal")
        Integer aldId);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByNameResponse")
    public ArrayOfAld searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param packId
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByPackIdResponse")
    public ArrayOfAld searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        int packId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.whatever.AldService.ArrayOfAld
     */
    @WebMethod
    @WebResult(name = "aldList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.AldService.SearchByProductIdResponse")
    public ArrayOfAld searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        int productId);

}
