
package com.whatever.AldService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AldService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/AldService.wsdl")
public class AldService_Service
    extends Service
{

    private final static URL ALDSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALDSERVICE_EXCEPTION;
    private final static QName ALDSERVICE_QNAME = new QName("urn:Vidal", "AldService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/AldService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALDSERVICE_WSDL_LOCATION = url;
        ALDSERVICE_EXCEPTION = e;
    }

    public AldService_Service() {
        super(__getWsdlLocation(), ALDSERVICE_QNAME);
    }

    public AldService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns AldService
     */
    @WebEndpoint(name = "AldServiceHttpPort")
    public AldService getAldServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "AldServiceHttpPort"), AldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AldService
     */
    @WebEndpoint(name = "AldServiceHttpPort")
    public AldService getAldServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "AldServiceHttpPort"), AldService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALDSERVICE_EXCEPTION!= null) {
            throw ALDSERVICE_EXCEPTION;
        }
        return ALDSERVICE_WSDL_LOCATION;
    }

}
