
package com.vidal.SfmgService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SfmgService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/SfmgService.wsdl")
public class SfmgService_Service
    extends Service
{

    private final static URL SFMGSERVICE_WSDL_LOCATION;
    private final static WebServiceException SFMGSERVICE_EXCEPTION;
    private final static QName SFMGSERVICE_QNAME = new QName("urn:Vidal", "SfmgService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/SfmgService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SFMGSERVICE_WSDL_LOCATION = url;
        SFMGSERVICE_EXCEPTION = e;
    }

    public SfmgService_Service() {
        super(__getWsdlLocation(), SFMGSERVICE_QNAME);
    }

    public SfmgService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SfmgService
     */
    @WebEndpoint(name = "SfmgServiceHttpPort")
    public SfmgService getSfmgServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "SfmgServiceHttpPort"), SfmgService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SfmgService
     */
    @WebEndpoint(name = "SfmgServiceHttpPort")
    public SfmgService getSfmgServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "SfmgServiceHttpPort"), SfmgService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SFMGSERVICE_EXCEPTION!= null) {
            throw SFMGSERVICE_EXCEPTION;
        }
        return SFMGSERVICE_WSDL_LOCATION;
    }

}
