
package com.vidal.DrugInteractionClassService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "drugInteractionClassService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DrugInteractionClassService {


    /**
     * 
     * @param drugInteractionClassId
     * @return
     *     returns com.vidal.DrugInteractionClassService.ArrayOfDrugInteractionClassSeverityCouple
     */
    @WebMethod
    @WebResult(name = "drugInteractionClassList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchAllInteractingClassesWithDrugInteractionClassId", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchAllInteractingClassesWithDrugInteractionClassId")
    @ResponseWrapper(localName = "searchAllInteractingClassesWithDrugInteractionClassIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchAllInteractingClassesWithDrugInteractionClassIdResponse")
    public ArrayOfDrugInteractionClassSeverityCouple searchAllInteractingClassesWithDrugInteractionClassId(
        @WebParam(name = "drugInteractionClassId", targetNamespace = "urn:Vidal")
        Integer drugInteractionClassId);

    /**
     * 
     * @param commonNameGroupId
     * @return
     *     returns com.vidal.DrugInteractionClassService.CommonNameGroupDrugInteractionClassList
     */
    @WebMethod
    @WebResult(name = "drugInteractionClassList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByCommonNameGroupIdResponse")
    public CommonNameGroupDrugInteractionClassList searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        Integer commonNameGroupId);

    /**
     * 
     * @param drugInteractionClassId
     * @return
     *     returns com.vidal.DrugInteractionClassService.DrugInteractionClass
     */
    @WebMethod
    @WebResult(name = "drugInteractionClass", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByIdResponse")
    public DrugInteractionClass searchById(
        @WebParam(name = "drugInteractionClassId", targetNamespace = "urn:Vidal")
        Integer drugInteractionClassId);

    /**
     * 
     * @param interactionId
     * @return
     *     returns com.vidal.DrugInteractionClassService.ArrayOfDrugInteractionClass
     */
    @WebMethod
    @WebResult(name = "drugInteractionClassList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByInteractionId", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByInteractionId")
    @ResponseWrapper(localName = "searchByInteractionIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByInteractionIdResponse")
    public ArrayOfDrugInteractionClass searchByInteractionId(
        @WebParam(name = "interactionId", targetNamespace = "urn:Vidal")
        Integer interactionId);

    /**
     * 
     * @param name
     * @return
     *     returns com.vidal.DrugInteractionClassService.ArrayOfDrugInteractionClass
     */
    @WebMethod
    @WebResult(name = "drugInteractionClassList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByNameResponse")
    public ArrayOfDrugInteractionClass searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param productId
     * @return
     *     returns com.vidal.DrugInteractionClassService.ArrayOfDrugInteractionClass
     */
    @WebMethod
    @WebResult(name = "drugInteractionClassList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.DrugInteractionClassService.SearchByProductIdResponse")
    public ArrayOfDrugInteractionClass searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        Integer productId);

}
