
package com.vidal.IndicationGroupService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IndicationGroupService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/IndicationGroupService.wsdl")
public class IndicationGroupService_Service
    extends Service
{

    private final static URL INDICATIONGROUPSERVICE_WSDL_LOCATION;
    private final static WebServiceException INDICATIONGROUPSERVICE_EXCEPTION;
    private final static QName INDICATIONGROUPSERVICE_QNAME = new QName("urn:Vidal", "IndicationGroupService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/IndicationGroupService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INDICATIONGROUPSERVICE_WSDL_LOCATION = url;
        INDICATIONGROUPSERVICE_EXCEPTION = e;
    }

    public IndicationGroupService_Service() {
        super(__getWsdlLocation(), INDICATIONGROUPSERVICE_QNAME);
    }

    public IndicationGroupService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IndicationGroupService
     */
    @WebEndpoint(name = "IndicationGroupServiceHttpPort")
    public IndicationGroupService getIndicationGroupServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "IndicationGroupServiceHttpPort"), IndicationGroupService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IndicationGroupService
     */
    @WebEndpoint(name = "IndicationGroupServiceHttpPort")
    public IndicationGroupService getIndicationGroupServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "IndicationGroupServiceHttpPort"), IndicationGroupService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INDICATIONGROUPSERVICE_EXCEPTION!= null) {
            throw INDICATIONGROUPSERVICE_EXCEPTION;
        }
        return INDICATIONGROUPSERVICE_WSDL_LOCATION;
    }

}
