
package com.vidal.WarningService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WarningService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/WarningService.wsdl")
public class WarningService_Service
    extends Service
{

    private final static URL WARNINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException WARNINGSERVICE_EXCEPTION;
    private final static QName WARNINGSERVICE_QNAME = new QName("urn:Vidal", "WarningService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/WarningService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WARNINGSERVICE_WSDL_LOCATION = url;
        WARNINGSERVICE_EXCEPTION = e;
    }

    public WarningService_Service() {
        super(__getWsdlLocation(), WARNINGSERVICE_QNAME);
    }

    public WarningService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WarningService
     */
    @WebEndpoint(name = "WarningServiceHttpPort")
    public WarningService getWarningServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "WarningServiceHttpPort"), WarningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarningService
     */
    @WebEndpoint(name = "WarningServiceHttpPort")
    public WarningService getWarningServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "WarningServiceHttpPort"), WarningService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WARNINGSERVICE_EXCEPTION!= null) {
            throw WARNINGSERVICE_EXCEPTION;
        }
        return WARNINGSERVICE_WSDL_LOCATION;
    }

}
