
package com.vidal.PackService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PackService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/PackService.wsdl")
public class PackService_Service
    extends Service
{

    private final static URL PACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException PACKSERVICE_EXCEPTION;
    private final static QName PACKSERVICE_QNAME = new QName("urn:Vidal", "PackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/PackService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PACKSERVICE_WSDL_LOCATION = url;
        PACKSERVICE_EXCEPTION = e;
    }

    public PackService_Service() {
        super(__getWsdlLocation(), PACKSERVICE_QNAME);
    }

    public PackService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PackService
     */
    @WebEndpoint(name = "PackServiceHttpPort")
    public PackService getPackServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "PackServiceHttpPort"), PackService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PackService
     */
    @WebEndpoint(name = "PackServiceHttpPort")
    public PackService getPackServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "PackServiceHttpPort"), PackService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PACKSERVICE_EXCEPTION!= null) {
            throw PACKSERVICE_EXCEPTION;
        }
        return PACKSERVICE_WSDL_LOCATION;
    }

}
