
package com.whatever.ApparatusService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ApparatusService", targetNamespace = "urn:Vidal", wsdlLocation = "file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/ApparatusService.wsdl")
public class ApparatusService_Service
    extends Service
{

    private final static URL APPARATUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPARATUSSERVICE_EXCEPTION;
    private final static QName APPARATUSSERVICE_QNAME = new QName("urn:Vidal", "ApparatusService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/SourceRepoAlt/agfa/sdb-connectors/fr/vidal/trunk/src/main/resources/wsdl/ApparatusService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPARATUSSERVICE_WSDL_LOCATION = url;
        APPARATUSSERVICE_EXCEPTION = e;
    }

    public ApparatusService_Service() {
        super(__getWsdlLocation(), APPARATUSSERVICE_QNAME);
    }

    public ApparatusService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ApparatusService
     */
    @WebEndpoint(name = "ApparatusServiceHttpPort")
    public ApparatusService getApparatusServiceHttpPort() {
        return super.getPort(new QName("urn:Vidal", "ApparatusServiceHttpPort"), ApparatusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApparatusService
     */
    @WebEndpoint(name = "ApparatusServiceHttpPort")
    public ApparatusService getApparatusServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Vidal", "ApparatusServiceHttpPort"), ApparatusService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPARATUSSERVICE_EXCEPTION!= null) {
            throw APPARATUSSERVICE_EXCEPTION;
        }
        return APPARATUSSERVICE_WSDL_LOCATION;
    }

}
