
package com.whatever.MoleculeService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "moleculeService", targetNamespace = "urn:Vidal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MoleculeService {


    /**
     * 
     * @param role
     * @param pageNumber
     * @param pageSize
     * @return
     *     returns com.whatever.MoleculeService.PagedResultMolecule
     */
    @WebMethod
    @WebResult(name = "pagedResultMolecule", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllMolecules", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.GetAllMolecules")
    @ResponseWrapper(localName = "getAllMoleculesResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.GetAllMoleculesResponse")
    public PagedResultMolecule getAllMolecules(
        @WebParam(name = "role", targetNamespace = "urn:Vidal")
        SubstanceRole role,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        Integer pageSize);

    /**
     * 
     * @param moleculeId
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildrenById", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.GetChildrenById")
    @ResponseWrapper(localName = "getChildrenByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.GetChildrenByIdResponse")
    public ArrayOfMolecule getChildrenById(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        Integer moleculeId);

    /**
     * 
     * @param moleculeId
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParentsById", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.GetParentsById")
    @ResponseWrapper(localName = "getParentsByIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.GetParentsByIdResponse")
    public ArrayOfMolecule getParentsById(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        Integer moleculeId);

    /**
     * 
     * @param allergyId
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAllergyId", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByAllergyId")
    @ResponseWrapper(localName = "searchByAllergyIdResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByAllergyIdResponse")
    public ArrayOfMolecule searchByAllergyId(
        @WebParam(name = "allergyId", targetNamespace = "urn:Vidal")
        Integer allergyId);

    /**
     * 
     * @param moleculeIds
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByIdsResponse")
    public ArrayOfMolecule searchByIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt moleculeIds);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByNameResponse")
    public ArrayOfMolecule searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

    /**
     * 
     * @param role
     * @param name
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameAndRoleWithIndexedVidalWithUsedInComposition", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByNameAndRoleWithIndexedVidalWithUsedInComposition")
    @ResponseWrapper(localName = "searchByNameAndRoleWithIndexedVidalWithUsedInCompositionResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchByNameAndRoleWithIndexedVidalWithUsedInCompositionResponse")
    public ArrayOfMolecule searchByNameAndRoleWithIndexedVidalWithUsedInComposition(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name,
        @WebParam(name = "role", targetNamespace = "urn:Vidal")
        SubstanceRole role);

    /**
     * 
     * @param moleculeIds
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOnlySecuredMoleculeByIds", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchOnlySecuredMoleculeByIds")
    @ResponseWrapper(localName = "searchOnlySecuredMoleculeByIdsResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchOnlySecuredMoleculeByIdsResponse")
    public ArrayOfMolecule searchOnlySecuredMoleculeByIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        ArrayOfInt moleculeIds);

    /**
     * 
     * @param name
     * @return
     *     returns com.whatever.MoleculeService.ArrayOfMolecule
     */
    @WebMethod
    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOnlySecuredMoleculeByName", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchOnlySecuredMoleculeByName")
    @ResponseWrapper(localName = "searchOnlySecuredMoleculeByNameResponse", targetNamespace = "urn:Vidal", className = "com.whatever.MoleculeService.SearchOnlySecuredMoleculeByNameResponse")
    public ArrayOfMolecule searchOnlySecuredMoleculeByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        String name);

}
